export type Product = {
  slug: string
  sku: string
  name: string
  shortDesc: string
  price: number | null  // null = Anfrage-Produkt ODER externalUrl-Angebot
  priceLabel?: string
  category: string
  flag: string
  image: string
  included: string[]
  notIncluded: string[]
  addons: string[]
  process: string[]
  hint: string
  inquiry?: boolean  // true = Kontaktformular statt Warenkorb
  externalUrl?: string  // gesetzt = Karte verlinkt direkt auf Partnerseite, kein interner Checkout
  tags: string[]
}

export const PRODUCTS: Product[] = [
  {
    slug: 'deutsche-ug-gruendung',
    sku: 'EUROPAN-DE-UG-001',
    name: 'Deutsche UG-Gründung',
    shortDesc: 'Gründung einer deutschen Unternehmergesellschaft (haftungsbeschränkt) nach Musterprotokoll – inklusive Vorbereitung der Gründungsdaten, notarieller Gründung und Handelsregistereintragung.',
    price: 698,
    category: 'Deutschland',
    flag: '🇩🇪',
    image: '/products/deutschland-300x300.png',
    included: [
      'Vorbereitung der Gründungsdaten',
      'Abstimmung des gewünschten Firmennamens',
      'Gründung nach Musterprotokoll',
      'Vorbereitung der notariellen Gründung',
      'Handelsregisteranmeldung',
      'Begleitung bis zur Eintragung',
      'Grundpaket mit einem Geschäftsführer und einem Gesellschafter',
    ],
    notIncluded: [
      'Bankkontoeröffnung',
      'Gewerbeanmeldung',
      'Laufende Buchhaltung',
      'Steuerliche Beratung',
      'Individuelle Satzung außerhalb des Musterprotokolls',
      'Laufende Geschäftsadresse, sofern nicht gesondert gebucht',
    ],
    addons: [
      'Ergänzende Geschäftsadresse / Postservice',
      'Verwaltungs- und Geschäftsführungsstrukturen nach Prüfung',
    ],
    process: [
      'Bestellung des Gründungspakets',
      'Übermittlung der erforderlichen Daten',
      'Prüfung und Abstimmung des gewünschten Firmennamens',
      'Vorbereitung der Gründungsunterlagen',
      'Notarielle Gründung und Handelsregisteranmeldung',
      'Eintragung der Gesellschaft',
    ],
    hint: 'Das Stammkapital der UG beträgt mindestens 1,00 EUR. Das Paket orientiert sich an einer Gründung mit einem Stammkapital von 1.000,00 EUR.',
    tags: ['UG', 'Unternehmergesellschaft', 'Deutschland', 'Firmengründung', 'haftungsbeschränkt'],
  },
  {
    slug: 'deutsche-gmbh-gruendung',
    sku: 'EUROPAN-DE-GMBH-001',
    name: 'Deutsche GmbH-Gründung',
    shortDesc: 'Gründung einer deutschen GmbH nach Musterprotokoll – inklusive Vorbereitung der Gründungsdaten, notarieller Gründung und Handelsregistereintragung.',
    price: 1298,
    category: 'Deutschland',
    flag: '🇩🇪',
    image: '/products/deutschland-300x300.png',
    included: [
      'Vorbereitung der Gründungsdaten',
      'Abstimmung des gewünschten Firmennamens',
      'Gründung nach Musterprotokoll',
      'Vorbereitung der notariellen Gründung',
      'Handelsregisteranmeldung',
      'Begleitung bis zur Eintragung',
      'Grundpaket mit einem Geschäftsführer und einem Gesellschafter',
    ],
    notIncluded: [
      'Bankkontoeröffnung',
      'Gewerbeanmeldung',
      'Laufende Buchhaltung',
      'Steuerliche Beratung',
      'Individuelle Satzung außerhalb des Musterprotokolls',
      'Laufende Geschäftsadresse, sofern nicht gesondert gebucht',
    ],
    addons: [
      'Ergänzende Office- oder Geschäftsadressen',
      'Postservice-Leistungen',
      'Verwaltungs- und Strukturierungsoptionen nach Prüfung',
    ],
    process: [
      'Bestellung des Gründungspakets',
      'Übermittlung der erforderlichen Daten',
      'Prüfung und Abstimmung des gewünschten Firmennamens',
      'Vorbereitung der Gründungsunterlagen',
      'Notarielle Gründung und Handelsregisteranmeldung',
      'Eintragung der Gesellschaft',
    ],
    hint: 'Das Stammkapital der GmbH beträgt grundsätzlich 25.000,00 EUR. Davon muss vor der Eintragung mindestens die gesetzlich erforderliche Einzahlung geleistet werden.',
    tags: ['GmbH', 'Deutschland', 'Firmengründung', 'Kapitalgesellschaft'],
  },
  {
    slug: 'englische-limited-gruenden',
    sku: 'EUROPAN-UK-LTD-001',
    name: 'Englische Limited gründen',
    shortDesc: 'Professionelle Gründung einer englischen Limited Company mit Vorbereitung der Gründungsdaten, Companies-House-Eintragung und verständlicher Begleitung.',
    price: 299,
    category: 'UK / Großbritannien',
    flag: '🇬🇧',
    image: '/products/uk-300x300.png',
    included: [
      'Vorprüfung der gewünschten Firmierung',
      'Vorbereitung der Gründungsdaten',
      'Gründung der UK Limited Company',
      'Eintragung bei Companies House',
      'Bereitstellung der Gründungsunterlagen',
      'Hinweise zu Director, Shareholder und PSC',
      'Hinweise zu den laufenden Registerpflichten',
      'Übergabe der relevanten Gesellschaftsdaten nach Eintragung',
    ],
    notIncluded: [
      'Registered Office / Serviceadresse in UK',
      'Steuerliche Beratung',
      'Laufende Buchhaltung und Compliance-Betreuung',
      'Bankkontoeröffnung',
      'Fintech- oder Payment-Anbieter-Eröffnung',
      'Apostillen, Beglaubigungen oder Übersetzungen',
    ],
    addons: [
      'Registered Office / Serviceadresse in UK',
      'Unterstützung bei Änderungen bestehender UK-Gesellschaften',
      'Name Change einer bestehenden Limited',
      'Share Transfer / Gesellschafterwechsel',
      'Vorbereitung für Bank-, Fintech- oder Payment-Anbieter',
      'Laufender Compliance- und Erinnerungsservice',
    ],
    process: [
      'Bestellung und Datenübermittlung',
      'Vorprüfung der gewünschten Firmierung',
      'Vorbereitung der Gründungsunterlagen',
      'Eintragung bei Companies House',
      'Übergabe der Gesellschaftsdaten',
    ],
    hint: 'Seit dem 18. November 2025 ist die Identitätsverifikation für Directors und PSCs rechtlich relevant. Steuerliche Pflichten bei Wohnsitz in Deutschland oder Österreich müssen gesondert geprüft werden.',
    tags: ['UK Ltd', 'Limited', 'Englische Limited', 'Großbritannien', 'Internationale Firmengründung'],
  },
  {
    slug: 'amerikanische-llc-gruenden',
    sku: 'EUROPAN-US-LLC-001',
    name: 'Amerikanische LLC gründen',
    shortDesc: 'Professionelle Vorbereitung und Begleitung bei der Gründung einer amerikanischen LLC für internationale Unternehmer, digitale Geschäftsmodelle und projektbezogene US-Strukturen.',
    price: 399,
    category: 'USA',
    flag: '🇺🇸',
    image: '/products/usa-300x300.png',
    included: [
      'Vorprüfung der gewünschten Firmierung',
      'Grundlegende Einordnung geeigneter US-Bundesstaaten',
      'Vorbereitung der Gründungsdaten',
      'Begleitung der LLC-Gründung im gewählten Bundesstaat',
      'Hinweise zu Member, Manager und Operating Agreement',
      'Hinweise zum Registered Agent',
      'Grundlegende Hinweise zum EIN-Thema',
      'Übergabe der relevanten Gesellschaftsdaten nach Gründung',
    ],
    notIncluded: [
      'Offizielle State Filing Fees',
      'Registered Agent Gebühren',
      'EIN-Antrag (als gesonderte Zusatzleistung verfügbar)',
      'Steuerliche Beratung',
      'Laufende Buchhaltung und Compliance-Betreuung',
      'Bankkontoeröffnung',
    ],
    addons: [
      'Registered Agent im gewählten Bundesstaat',
      'Operating Agreement',
      'EIN-Unterstützung für internationale Antragsteller',
      'US-Adresse oder Mail Forwarding',
      'Vorbereitung für Bank-, Fintech- oder Payment-Anbieter',
      'Apostille oder beglaubigte Gründungsunterlagen',
    ],
    process: [
      'Bestellung und Datenübermittlung',
      'Auswahl des geeigneten Bundesstaats',
      'Vorprüfung der Firmierung',
      'Vorbereitung der Gründungsunterlagen',
      'LLC-Gründung im gewählten Bundesstaat',
      'Übergabe der Gesellschaftsdaten',
    ],
    hint: 'Die Kosten, Pflichten und sinnvolle Gestaltung hängen stark vom gewählten Bundesstaat ab. State Filing Fees und Registered Agent Gebühren sind nicht im Basispreis enthalten.',
    tags: ['US LLC', 'LLC', 'USA', 'Amerikanische LLC', 'Internationale Firmengründung'],
  },
  {
    slug: 'hong-kong-limited-gruenden',
    sku: 'EUROPAN-HK-LTD-001',
    name: 'Hong Kong Limited gründen',
    shortDesc: 'Professionelle Gründung einer Hong Kong Limited mit Registered Office und Company Secretary. Geeignet für Asien-Geschäft, E-Commerce, Handel und digitale Geschäftsmodelle.',
    price: 899,
    category: 'Hong Kong',
    flag: '🇭🇰',
    image: '/products/hngkong-300x300.png',
    included: [
      'Vorprüfung der gewünschten Firmierung',
      'Vorbereitung der Gründungsdaten',
      'Gründung einer Hong Kong Limited',
      'Registered Office in Hong Kong für den Startzeitraum',
      'Company Secretary in Hong Kong für den Startzeitraum',
      'Hinweise zu Director, Shareholder und Company Secretary',
      'Grundlegende Hinweise zur Business Registration',
      'Übergabe der relevanten Gesellschaftsdaten nach Gründung',
    ],
    notIncluded: [
      'Offizielle Behördengebühren (soweit separat berechnet)',
      'Business Registration Fee und Levy',
      'Steuerliche Beratung',
      'Laufende Buchhaltung, Audit oder Accounting Services',
      'Bankkontoeröffnung',
      'Fintech- oder Payment-Anbieter-Eröffnung',
      'Apostillen, Beglaubigungen oder Übersetzungen',
    ],
    addons: [
      'Verlängerung Registered Office',
      'Verlängerung Company Secretary',
      'Business-Registration-Verlängerung',
      'Accounting- und Audit-Vorbereitung',
      'Unterstützung bei Bank-, Fintech- oder Payment-Anbieter-Vorbereitung',
      'Laufender Compliance- und Erinnerungsservice',
    ],
    process: [
      'Bestellung und Datenübermittlung',
      'Vorprüfung der Firmierung',
      'Vorbereitung der Gründungsunterlagen',
      'Gründung der Hong Kong Limited',
      'Einrichtung von Registered Office und Company Secretary',
      'Übergabe der Gesellschaftsdaten',
    ],
    hint: 'Bankkonto, Fintech-Zugang oder Payment-Anbieter können nicht garantiert werden. Die Akzeptanz durch Banken hängt von Geschäftsmodell, Dokumentation und Compliance-Prüfung des jeweiligen Anbieters ab.',
    tags: ['Hong Kong Limited', 'HK Ltd', 'Asien', 'Internationale Firmengründung'],
  },
  {
    slug: 'irische-limited-gruenden',
    sku: 'EUROPAN-IE-LTD-001',
    name: 'Irische Limited gründen',
    shortDesc: 'Professionelle Vorbereitung und Begleitung bei der Gründung einer irischen Limited Company. Geeignet für EU-nahe Projektstrukturen und internationale Unternehmer.',
    price: 1199,
    category: 'Irland',
    flag: '🇮🇪',
    image: '/products/irland-300x300.png',
    included: [
      'Vorprüfung der gewünschten Firmierung',
      'Grundlegende Prüfung, ob eine irische LTD sinnvoll erscheint',
      'Einordnung der Director- und EEA-Resident-Director-Thematik',
      'Vorbereitung der Gründungsdaten',
      'Begleitung der irischen LTD-Gründung',
      'Hinweise zu Director, Shareholder und Company Secretary',
      'Hinweise zu Beneficial Ownership und RBO-Thematik',
      'Übergabe der relevanten Gesellschaftsdaten nach Gründung',
    ],
    notIncluded: [
      'Irischer Resident Director',
      'Bond oder Ersatzlösungen für fehlenden EEA-Resident-Director',
      'Registered Office (soweit nicht separat vereinbart)',
      'Company Secretary (soweit nicht separat vereinbart)',
      'Steuerliche Beratung',
      'Laufende Buchhaltung, Accounting, Audit',
      'Bankkontoeröffnung',
    ],
    addons: [
      'Registered Office in Irland',
      'Company Secretary',
      'Unterstützung bei RBO-/Beneficial-Owner-Themen',
      'Revenue-/Tax-Registration-Vorbereitung',
      'Accounting- und Compliance-Vorbereitung',
      'Laufender Compliance- und Erinnerungsservice',
    ],
    process: [
      'Bestellung und Datenübermittlung',
      'Grundlegende Prüfung der Struktur und Director-Anforderungen',
      'Vorprüfung der Firmierung',
      'Vorbereitung der Gründungsunterlagen',
      'Begleitung der irischen LTD-Gründung',
      'Übergabe der Gesellschaftsdaten',
    ],
    hint: 'Die irische LTD ist eine seriöse EU-Gesellschaft mit strengen Register- und Compliance-Anforderungen. Director-Themen, Identitätsnachweise und wirtschaftlich Berechtigte müssen sorgfältig geprüft werden.',
    tags: ['Irish LTD', 'Irische Limited', 'EU Gesellschaft', 'Irland', 'Internationale Firmengründung'],
  },
  {
    slug: 'neuseelaendische-limited-gruenden',
    sku: 'EUROPAN-NZ-LTD-001',
    name: 'Neuseeländische Limited gründen',
    shortDesc: 'Professionelle Vorbereitung und Begleitung bei der Gründung einer neuseeländischen Limited Company mit lokaler Director-/Adressstruktur für den Startzeitraum.',
    price: 2999,
    category: 'Neuseeland',
    flag: '🇳🇿',
    image: '/products/nz-300x300.png',
    included: [
      'Vorprüfung der gewünschten Firmierung',
      'Grundlegende Prüfung, ob eine neuseeländische Ltd sinnvoll erscheint',
      'Einordnung der Director-Residency-Anforderungen',
      'Vorbereitung der Gründungsdaten',
      'Begleitung der neuseeländischen Ltd-Gründung',
      'Lokale Director-/Adressstruktur für den Startzeitraum (nach Prüfung)',
      'Hinweise zu Director, Shareholder und Shares',
      'Hinweise zu Registered Office, Serviceadresse und Kommunikationsadresse',
      'Übergabe der relevanten Gesellschaftsdaten nach Gründung',
    ],
    notIncluded: [
      'Regulierte Finanzdienstleistungen',
      'Bank-, Investment- oder erlaubnispflichtige Tätigkeiten',
      'Dauerhafte Director-/Adressleistungen über den Startzeitraum hinaus',
      'Nominee-Strukturen ohne wirtschaftliche Transparenz',
      'Offizielle Registergebühren (soweit separat berechnet)',
      'Steuerliche Beratung',
      'Laufende Buchhaltung und Accounting',
      'Bankkontoeröffnung',
    ],
    addons: [
      'Verlängerung lokaler Director-/Adressstruktur',
      'Registered Office in Neuseeland',
      'Inland-Revenue-/Tax-Registration-Vorbereitung',
      'Accounting- und Compliance-Vorbereitung',
      'Laufender Compliance- und Erinnerungsservice',
      'Unterstützung bei Bank-, Fintech- oder Payment-Anbieter-Vorbereitung',
    ],
    process: [
      'Bestellung und Datenübermittlung',
      'Prüfung der Director-Residency-Anforderungen',
      'Vorprüfung der Firmierung',
      'Vorbereitung der Gründungsunterlagen',
      'Begleitung der NZ Ltd-Gründung',
      'Übergabe der Gesellschaftsdaten',
    ],
    hint: 'Die Annahme dieses Auftrags steht unter Prüfvorbehalt. Die Director-Residency-Anforderung sollte nicht unterschätzt werden. Nicht jeder internationale Kunde kann ohne passende lokale Director-Struktur eine neuseeländische Gesellschaft führen.',
    tags: ['NZ Ltd', 'Neuseeländische Limited', 'New Zealand Limited', 'Neuseeland', 'Internationale Firmengründung'],
  },
  {
    slug: 'nevis-llc-gruenden',
    sku: 'EUROPAN-NEVIS-LLC-001',
    name: 'Nevis LLC gründen',
    shortDesc: 'Gründung einer Nevis LLC als Premium-Struktur für internationale Asset Protection, Holding- und Vermögensverwaltungsmodelle – nur mit Due Diligence und klarer Zweckprüfung.',
    price: 3490,
    category: 'Nevis',
    flag: '🏝️',
    image: '/products/nevis-300x300.png',
    included: [
      'Vorprüfung der Nevis-LLC-Struktur',
      'Koordination mit lizenziertem Registered Agent in Nevis',
      'Namens- und Strukturprüfung',
      'Vorbereitung von Articles of Organization und Operating Agreement-Struktur',
      'Einrichtung der Mitglieder- und Managerstruktur',
      'Gründungsdokumentation und Übergabe der Gesellschaftsunterlagen',
      'Hinweise zu Annual Renewal, Good Standing und laufender Administration',
    ],
    notIncluded: [
      'Staatliche Gebühren',
      'Registered-Agent-/Registered-Office-Kosten',
      'Bankkontoeröffnung',
      'Komplexe Asset-Protection-Strukturen (separat zu prüfen)',
      'Nominee-/Treuhandfunktionen (separat zu prüfen)',
      'Steuerliche Beratung',
    ],
    addons: [
      'Bankkonto-Vorbereitung nach gesonderter Prüfung',
      'Besondere Asset-Protection-Strukturen nach Prüfung',
      'Nominee-/Treuhandfunktionen nach Prüfung',
      'Komplexe Holdingmodelle nach individuellem Angebot',
    ],
    process: [
      'Bestellung und Due-Diligence-Prüfung',
      'Koordination mit Registered Agent in Nevis',
      'Namens- und Strukturprüfung',
      'Vorbereitung der Gründungsunterlagen',
      'Gründung der Nevis LLC',
      'Übergabe der Gesellschaftsdaten',
    ],
    hint: 'Nicht geeignet für: nachträgliche Vereitelung bestehender Gläubigerrechte, Steuerhinterziehung, verschleierte wirtschaftlich Berechtigte oder nicht dokumentierte Zahlungsflüsse. Preis zuzüglich staatlicher Gebühren und Registered-Agent-Kosten.',
    tags: ['Nevis LLC', 'Asset Protection', 'Offshore', 'Internationale Firmengründung', 'Nevis'],
  },
  {
    slug: 'uk-limited-nominee-treuhandadministration',
    sku: 'EUROPAN-UK-NOMINEE-001',
    name: 'UK Limited Nominee- und Treuhandadministration',
    shortDesc: 'Professionelle Nominee- und Treuhandverwaltung für UK Limited Strukturen — dokumentiert, compliance-orientiert und vollständig transparent bezüglich wirtschaftlich Berechtigter.',
    price: null,
    priceLabel: 'Ab individuelles Angebot nach Prüfung',
    inquiry: true,
    category: 'UK / Großbritannien',
    flag: '🇬🇧',
    image: '/products/UKnominee-300x300.png',
    included: [
      'KYC-/AML-Prüfung und Dokumentation wirtschaftlich Berechtigter',
      'Nominee Shareholder / Treuhandverwaltung nach Mandatsprüfung',
      'Nominee Director nach Einzelfallprüfung',
      'Mandats-, Weisungs- und Beschlussdokumentation',
      'Koordination mit UK-Company-Secretary und Registered Office',
      'Laufende Companies-House-Compliance und Annual Confirmation Statement',
    ],
    notIncluded: [
      'Anonyme oder verdeckte Gesellschaftsstrukturen',
      'Verschleierung wirtschaftlich Berechtigter (PSC)',
      'Steuerhinterziehung oder Umgehung steuerlicher Pflichten',
      'Nicht dokumentierte Zahlungsflüsse',
    ],
    addons: [
      'Laufende Buchhaltung und Accounting',
      'Registered Office-Verlängerung',
      'Bankkonto- und Zahlungsadministration nach gesonderter Prüfung',
    ],
    process: [
      'Anfrage und erste Strukturbeschreibung',
      'KYC-/AML- und Compliance-Prüfung',
      'Mandatsannahme und Vertragsgestaltung',
      'Einrichtung der Nominee-/Treuhandstruktur',
      'Laufende Administration und Dokumentation',
    ],
    hint: 'Dieses Angebot dient ausschließlich der professionellen, dokumentierten Gesellschaftsverwaltung. Eine Mandatsannahme erfolgt nur nach vollständiger KYC- und Compliance-Prüfung.',
    tags: ['UK Nominee', 'Treuhand', 'UK Limited', 'Gesellschaftsverwaltung'],
  },
  {
    slug: 'internationale-nominee-treuhandadministration',
    sku: 'EUROPAN-INT-NOMINEE-TRUST-001',
    name: 'Internationale Nominee- und Treuhandadministration',
    shortDesc: 'Jurisdiktionsübergreifende Nominee-, Treuhand- und Mandatsadministration für internationale Gesellschaftsstrukturen — z. B. Hong Kong, Irland, Belize, Nevis, Cayman, Australien oder Neuseeland.',
    price: null,
    priceLabel: 'Ab €2.490 — individuelles Angebot nach Due Diligence',
    inquiry: true,
    category: 'International',
    flag: '🌐',
    image: '/products/int_nominee-300x300.png',
    included: [
      'Internationale Struktur- und Jurisdiktionsprüfung',
      'KYC-/AML-/Sanktions- und Risikoprüfung der Beteiligten',
      'Prüfung und Dokumentation wirtschaftlich Berechtigter / UBO / PSC / RBO',
      'Prüfung von Steueransässigkeit, Mittelherkunft und Geschäftszweck',
      'Koordination mit lokalen Registered Agents und Company Secretaries',
      'Nominee Shareholder / Treuhandverwaltung nach Mandatsprüfung',
      'Mandats-, Weisungs- und Beschlussdokumentation',
      'Laufende Compliance-, Register- und Renewal-Betreuung',
    ],
    notIncluded: [
      'Anonyme oder verdeckte Gesellschaftsstrukturen',
      'Verschleierung wirtschaftlich Berechtigter',
      'Steuerhinterziehung oder Umgehung steuerlicher Pflichten',
      'Verdeckte Drittzahlungen oder nicht nachvollziehbare Zahlungsflüsse',
      'Insolvenzverschleppung oder Gläubigerbenachteiligung',
    ],
    addons: [
      'Bankkonto- und Zahlungsadministration nach gesonderter Prüfung',
      'Multi-Jurisdiction-Holding-Strukturen nach individuellem Angebot',
    ],
    process: [
      'Anfrage und Strukturbeschreibung',
      'Internationale Due-Diligence-Prüfung',
      'Struktur- und Jurisdiktionsanalyse',
      'Mandatsannahme nach Prüfung',
      'Einrichtung der internationalen Struktur',
      'Laufende Compliance-Administration',
    ],
    hint: 'Dieses Angebot ist kein automatisch bestellbares Standardprodukt. Die endgültige Annahme, Strukturfreigabe und Preisbestätigung erfolgen ausschließlich nach individueller Due-Diligence-Prüfung. Nominee Director ab €7.900/Jahr, komplexe Strukturen ab €14.900/Jahr.',
    tags: ['Internationale Nominee', 'Treuhand', 'Asset Protection', 'Holding', 'Multi-Jurisdiction'],
  },
  {
    slug: 'geschaeftsadresse-pan-office',
    sku: 'EUROPAN-PANOFFICE-ADDR-001',
    name: 'Geschäftsadresse buchen',
    shortDesc: 'Digitale Geschäftsadresse an über 100 Standorten weltweit — sofort buchbar, mit digitaler Postverwaltung. Ab 3 Standorten in einer Buchung gilt automatisch der Mengenrabatt.',
    price: null,
    priceLabel: 'Ab €29,00/Monat — direkt bei pan-office.de',
    category: 'PAN21-Netzwerk',
    flag: '📍',
    image: 'https://pan-office.de/logo.png',
    included: [
      'Über 100 Standorte weltweit zur Wahl',
      'Digitale Postverwaltung',
      'Sofort buchbar, kein Mietvertrag',
      'Mengenrabatt ab 3 Standorten',
      '2% EUROPAN-Bonus bei jeder Buchung',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'Dieses Angebot wird direkt bei pan-office.de gebucht — dort sind die aktuellen Standorte, Preise und Verfügbarkeiten immer live einsehbar.',
    externalUrl: 'https://pan-office.de/clients',
    tags: ['Geschäftsadresse', 'Postbox', 'pan-office'],
  },
  {
    slug: 'europan-guthaben-aufladen',
    sku: 'EUROPAN-VOUCHER-001',
    name: 'EUROPAN-Guthaben aufladen',
    shortDesc: 'Laden Sie Ihr EUROPAN-Guthaben direkt auf — per Kreditkarte oder Überweisung, wählbarer Betrag. Einlösbar netzwerkweit, u.a. hier im Shop für den Doppel-Wums-Bonus.',
    price: null,
    priceLabel: 'Wählbarer Betrag — direkt bei europan.group',
    category: 'PAN21-Netzwerk',
    flag: '🎁',
    image: 'https://europan.group/europan-logo.png',
    included: [
      'Sofortige Gutschrift bei Kartenzahlung',
      'Wählbarer Betrag',
      'Netzwerkweit einlösbar (Shop, pan-office.de u.a.)',
      'Voraussetzung für den Doppel-Wums-Bonus',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'Dieses Angebot wird direkt bei europan.group abgewickelt.',
    externalUrl: 'https://europan.group/buy',
    tags: ['EUROPAN', 'Guthaben', 'Gutschein'],
  },
  {
    slug: 'webhosting-1euro-hosting',
    sku: 'EUROPAN-HOSTING-001',
    name: 'WordPress-Webhosting',
    shortDesc: 'WordPress-Hosting ab 1 €/Monat — monatlich kündbar, mit kostenloser Subdomain oder eigener Domain. Ideal als Ergänzung zur neuen Geschäftsadresse oder Firmengründung.',
    price: null,
    priceLabel: 'Ab €1,00/Monat — direkt bei 1euro-hosting.de',
    category: 'PAN21-Netzwerk',
    flag: '🌐',
    image: 'https://1euro-hosting.de/logo.png',
    included: [
      'WordPress-Hosting ab 1 €/Monat',
      'Monatlich kündbar',
      'Kostenlose Subdomain oder eigene Domain ab 9,90 €/Jahr',
      'Basic (3 €) und Pro (9,90 €) ohne Werbeeinblendungen',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'Dieses Angebot wird direkt bei 1euro-hosting.de gebucht.',
    externalUrl: 'https://1euro-hosting.de',
    tags: ['Hosting', 'WordPress', 'Webhosting'],
  },
]

export const CATEGORIES = [
  { id: 'alle', label: 'Alle' },
  { id: 'PAN21-Netzwerk', label: '⭐ PAN21-Netzwerk' },
  { id: 'Deutschland', label: '🇩🇪 Deutschland' },
  { id: 'UK / Großbritannien', label: '🇬🇧 UK' },
  { id: 'USA', label: '🇺🇸 USA' },
  { id: 'Hong Kong', label: '🇭🇰 Hong Kong' },
  { id: 'Irland', label: '🇮🇪 Irland' },
  { id: 'Neuseeland', label: '🇳🇿 Neuseeland' },
  { id: 'Nevis', label: '🏝️ Nevis' },
  { id: 'International', label: '🌐 International' },
]
