import { PRODUCTS, Product } from './products'

// English translations for the PAN21 Shop product catalogue.
// Only translatable copy lives here (name, shortDesc, priceLabel, the four
// bullet-list fields, hint and tags). Everything else — slug, sku, price,
// category id, flag, image, heroImage, inquiry, externalUrl — is the single
// source of truth in lib/products.ts and is merged in automatically by
// getProductsEn() below, so a price or image change never needs to be
// duplicated here.
export type ProductTranslation = {
  name: string
  shortDesc: string
  priceLabel?: string
  included: string[]
  notIncluded: string[]
  addons: string[]
  process: string[]
  hint: string
  tags: string[]
}

export const PRODUCT_TRANSLATIONS: Record<string, ProductTranslation> = {
  'deutsche-ug-gruendung': {
    name: 'German UG Formation',
    shortDesc: 'Formation of a German Unternehmergesellschaft (haftungsbeschränkt) under the standard model protocol — including preparation of the incorporation data, notarial formation and commercial register entry.',
    included: [
      'Preparation of the incorporation data',
      'Coordination of the desired company name',
      'Formation under the standard model protocol (Musterprotokoll)',
      'Preparation of the notarial formation',
      'Commercial register filing',
      'Support through to registration',
      'Basic package with one managing director and one shareholder',
    ],
    notIncluded: [
      'Bank account opening',
      'Trade registration (Gewerbeanmeldung)',
      'Ongoing bookkeeping',
      'Tax advice',
      'Individual articles of association outside the model protocol',
      'Ongoing business address, unless booked separately',
    ],
    addons: [
      'Supplementary business address / mail service',
      'Administration and management structures, subject to review',
    ],
    process: [
      'Order the formation package',
      'Submit the required data',
      'Review and coordination of the desired company name',
      'Preparation of the formation documents',
      'Notarial formation and commercial register filing',
      'Registration of the company',
    ],
    hint: 'The UG\'s share capital is at least €1.00. This package is based on a formation with share capital of €1,000.00.',
    tags: ['UG', 'Unternehmergesellschaft', 'Germany', 'Company formation', 'Limited liability'],
  },
  'deutsche-gmbh-gruendung': {
    name: 'German GmbH Formation',
    shortDesc: 'Formation of a German GmbH under the standard model protocol — including preparation of the incorporation data, notarial formation and commercial register entry.',
    included: [
      'Preparation of the incorporation data',
      'Coordination of the desired company name',
      'Formation under the standard model protocol (Musterprotokoll)',
      'Preparation of the notarial formation',
      'Commercial register filing',
      'Support through to registration',
      'Basic package with one managing director and one shareholder',
    ],
    notIncluded: [
      'Bank account opening',
      'Trade registration (Gewerbeanmeldung)',
      'Ongoing bookkeeping',
      'Tax advice',
      'Individual articles of association outside the model protocol',
      'Ongoing business address, unless booked separately',
    ],
    addons: [
      'Supplementary office or business addresses',
      'Mail service',
      'Administration and structuring options, subject to review',
    ],
    process: [
      'Order the formation package',
      'Submit the required data',
      'Review and coordination of the desired company name',
      'Preparation of the formation documents',
      'Notarial formation and commercial register filing',
      'Registration of the company',
    ],
    hint: 'The GmbH\'s share capital is generally €25,000.00, of which at least the legally required payment must be made before registration.',
    tags: ['GmbH', 'Germany', 'Company formation', 'Corporation'],
  },
  'englische-limited-gruenden': {
    name: 'Form an English Limited Company',
    shortDesc: 'Professional formation of an English Limited Company, including personal guidance through the Companies House identity verification made mandatory by the ECCTA reform, preparation of the incorporation data and registration.',
    included: [
      'Pre-check of the desired company name',
      'Preparation of the incorporation data',
      'Personal guidance through the Companies House identity verification (mandatory ID-check account for Director/PSC)',
      'Formation of the UK Limited Company',
      'Registration with Companies House',
      'Provision of the formation documents',
      'Guidance on Director, Shareholder and PSC',
      'Guidance on ongoing register obligations',
      'Handover of the relevant company data after registration',
    ],
    notIncluded: [
      'Registered Office / service address in the UK',
      'Tax advice',
      'Ongoing bookkeeping and compliance support',
      'Bank account opening',
      'Fintech or payment provider onboarding',
      'Apostilles, certifications or translations',
    ],
    addons: [
      'Registered Office / service address in the UK',
      'Support with changes to existing UK companies',
      'Name change of an existing Limited',
      'Share transfer / change of shareholders',
      'Preparation for bank, fintech or payment provider applications',
      'Ongoing compliance and reminder service',
    ],
    process: [
      'Order and data submission',
      'Pre-check of the desired company name',
      'Guidance through the Companies House identity verification (ID-check account)',
      'Preparation of the formation documents',
      'Registration with Companies House',
      'Handover of the company data',
    ],
    hint: 'Since 18 November 2025, identity verification for Directors and PSCs at Companies House has been a legal requirement. The formation price deliberately exceeds the pure statutory fees, because we personally guide and advise you through this verification process — without a correctly completed verification, registration is no longer possible. Tax obligations for residents of Germany or Austria must be reviewed separately.',
    tags: ['UK Ltd', 'Limited', 'English Limited', 'United Kingdom', 'International company formation'],
  },
  'amerikanische-llc-gruenden': {
    name: 'Form an American LLC',
    shortDesc: 'Professional preparation and support for forming an American LLC for international entrepreneurs, digital business models and project-based US structures.',
    included: [
      'Pre-check of the desired company name',
      'A 30-minute support call in which we clarify your complete private and business circumstances and then determine the most suitable formation type and US state for you',
      'Preparation of the incorporation data',
      'Support with the LLC formation in the chosen state',
      'Guidance on Member, Manager and Operating Agreement',
      'Guidance on the Registered Agent',
      'Basic guidance on the EIN topic',
      'Handover of the relevant company data after formation',
    ],
    notIncluded: [
      'Official state filing fees',
      'Registered Agent fees',
      'EIN application (available as a separate add-on)',
      'Tax advice',
      'Ongoing bookkeeping and compliance support',
      'Bank account opening',
    ],
    addons: [
      'Registered Agent in the chosen state',
      'Operating Agreement',
      'EIN support for international applicants',
      'US address or mail forwarding',
      'Preparation for bank, fintech or payment provider applications',
      'Apostille or certified formation documents',
    ],
    process: [
      'Order and data submission',
      'Selection of the suitable state',
      'Pre-check of the company name',
      'Preparation of the formation documents',
      'LLC formation in the chosen state',
      'Handover of the company data',
    ],
    hint: 'Costs, obligations and the most sensible structure depend heavily on the state chosen. State filing fees and Registered Agent fees are not included in the base price.',
    tags: ['US LLC', 'LLC', 'USA', 'American LLC', 'International company formation'],
  },
  'hong-kong-limited-gruenden': {
    name: 'Form a Hong Kong Limited',
    shortDesc: 'Professional formation of a Hong Kong Limited with Registered Office and Company Secretary. Suitable for Asia business, e-commerce, trading and digital business models.',
    included: [
      'Pre-check of the desired company name',
      'Preparation of the incorporation data',
      'Formation of a Hong Kong Limited',
      'Registered Office in Hong Kong for the initial period',
      'Company Secretary in Hong Kong for the initial period',
      'Guidance on Director, Shareholder and Company Secretary',
      'Basic guidance on Business Registration',
      'Handover of the relevant company data after formation',
    ],
    notIncluded: [
      'Official government fees (where charged separately)',
      'Business Registration Fee and levy',
      'Tax advice',
      'Ongoing bookkeeping, audit or accounting services',
      'Bank account opening',
      'Fintech or payment provider onboarding',
      'Apostilles, certifications or translations',
    ],
    addons: [
      'Registered Office renewal',
      'Company Secretary renewal',
      'Business Registration renewal',
      'Accounting and audit preparation',
      'Support preparing bank, fintech or payment provider applications',
      'Ongoing compliance and reminder service',
    ],
    process: [
      'Order and data submission',
      'Pre-check of the company name',
      'Preparation of the formation documents',
      'Formation of the Hong Kong Limited',
      'Set-up of Registered Office and Company Secretary',
      'Handover of the company data',
    ],
    hint: 'A bank account, fintech access or payment provider cannot be guaranteed. Acceptance by banks depends on the business model, documentation and the respective provider\'s compliance review.',
    tags: ['Hong Kong Limited', 'HK Ltd', 'Asia', 'International company formation'],
  },
  'irische-limited-gruenden': {
    name: 'Form an Irish Limited Company',
    shortDesc: 'Professional preparation and support for forming an Irish Limited Company. Suitable for EU-adjacent project structures and international entrepreneurs.',
    included: [
      'Pre-check of the desired company name',
      'Basic assessment of whether an Irish LTD makes sense',
      'Assessment of the Director and EEA-resident-director topic',
      'Preparation of the incorporation data',
      'Support with the Irish LTD formation',
      'Guidance on Director, Shareholder and Company Secretary',
      'Guidance on beneficial ownership and the RBO topic',
      'Handover of the relevant company data after formation',
    ],
    notIncluded: [
      'Irish resident director',
      'Bond or alternative solutions for a missing EEA-resident director',
      'Registered Office (unless separately agreed)',
      'Company Secretary (unless separately agreed)',
      'Tax advice',
      'Ongoing bookkeeping, accounting, audit',
      'Bank account opening',
    ],
    addons: [
      'Registered Office in Ireland',
      'Company Secretary',
      'Support with RBO / beneficial-owner matters',
      'Revenue / tax registration preparation',
      'Accounting and compliance preparation',
      'Ongoing compliance and reminder service',
    ],
    process: [
      'Order and data submission',
      'Basic review of the structure and director requirements',
      'Pre-check of the company name',
      'Preparation of the formation documents',
      'Support with the Irish LTD formation',
      'Handover of the company data',
    ],
    hint: 'The Irish LTD is a reputable EU company with strict register and compliance requirements. Director matters, proof of identity and beneficial owners must be carefully reviewed.',
    tags: ['Irish LTD', 'Irish Limited', 'EU company', 'Ireland', 'International company formation'],
  },
  'neuseelaendische-limited-gruenden': {
    name: 'Form a New Zealand Limited Company',
    shortDesc: 'Professional preparation and support for forming a New Zealand Limited Company with a local director/address structure for the start-up period.',
    included: [
      'Pre-check of the desired company name',
      'Basic assessment of whether a New Zealand Ltd makes sense',
      'Assessment of the director-residency requirements',
      'Preparation of the incorporation data',
      'Support with the New Zealand Ltd formation',
      'Local director/address structure for the start-up period (subject to review)',
      'Guidance on Director, Shareholder and Shares',
      'Guidance on Registered Office, service address and communication address',
      'Handover of the relevant company data after formation',
    ],
    notIncluded: [
      'Regulated financial services',
      'Banking, investment or licence-requiring activities',
      'Permanent director/address services beyond the start-up period',
      'Nominee structures without economic transparency',
      'Official register fees (where charged separately)',
      'Tax advice',
      'Ongoing bookkeeping and accounting',
      'Bank account opening',
    ],
    addons: [
      'Renewal of the local director/address structure',
      'Registered Office in New Zealand',
      'Inland Revenue / tax registration preparation',
      'Accounting and compliance preparation',
      'Ongoing compliance and reminder service',
      'Support preparing bank, fintech or payment provider applications',
    ],
    process: [
      'Order and data submission',
      'Review of the director-residency requirements',
      'Pre-check of the company name',
      'Preparation of the formation documents',
      'Support with the NZ Ltd formation',
      'Handover of the company data',
    ],
    hint: 'Acceptance of this order is subject to review. The director-residency requirement should not be underestimated. Not every international client can run a New Zealand company without a suitable local director structure.',
    tags: ['NZ Ltd', 'New Zealand Limited', 'New Zealand', 'International company formation'],
  },
  'belize-llc-gruenden': {
    name: 'Form a Belize LLC — Asset Protection Company Formation',
    shortDesc: 'Formation of a Belize LLC for international holding, wealth-management and asset-protection structures — with Registered Agent, due-diligence review and a clear compliance boundary.',
    included: [
      'Pre-check of the planned Belize LLC structure',
      'Name and structure review',
      'Coordination with the Registered Agent / Registered Office',
      'Preparation of the incorporation data and member structure',
      'Integration of an Operating Agreement / internal structure as needed',
      'Formation documentation and handover of the company documents',
      'Guidance on renewal, good standing, accounting records and ongoing administration',
    ],
    notIncluded: [
      'Retroactive shielding of assets from existing creditors',
      'Bank account opening (only after separate review)',
      'Ongoing administration, nominee/trustee functions (reviewed separately)',
      'Complex holding models (reviewed separately)',
      'Tax advice',
    ],
    addons: [
      'Digital bank / fintech pre-check',
      'International banking solution pre-check',
      'Complex bank review / high-risk profile',
      'Standard renewal & good-standing support (annual)',
      'Premium administration with compliance support (annual)',
      'Extended asset-protection / holding structure on request',
    ],
    process: [
      'Order and due-diligence review',
      'Coordination with the Registered Agent in Belize',
      'Name and structure review',
      'Preparation of the formation documents',
      'Formation of the Belize LLC',
      'Handover of the company data',
    ],
    hint: 'Asset protection does not mean defeating legitimate claims. Not suitable for tax evasion, prejudicing creditors, insolvency abuse, concealed beneficial owners or retroactive asset transfers. Price plus government fees, Registered Agent/Registered Office costs and options.',
    tags: ['Belize LLC', 'Asset protection', 'Holding', 'International company formation', 'Belize'],
  },
  'nevis-llc-gruenden': {
    name: 'Form a Nevis LLC',
    shortDesc: 'Formation of a Nevis LLC as a premium structure for international asset protection, holding and wealth-management models — only with due diligence and a clear purpose review.',
    included: [
      'Pre-check of the Nevis LLC structure',
      'Coordination with a licensed Registered Agent in Nevis',
      'Name and structure review',
      'Preparation of Articles of Organization and Operating Agreement structure',
      'Set-up of the member and manager structure',
      'Formation documentation and handover of the company documents',
      'Guidance on annual renewal, good standing and ongoing administration',
    ],
    notIncluded: [
      'Government fees',
      'Registered Agent / Registered Office costs',
      'Bank account opening',
      'Complex asset-protection structures (reviewed separately)',
      'Nominee/trustee functions (reviewed separately)',
      'Tax advice',
    ],
    addons: [
      'Bank account preparation after separate review',
      'Special asset-protection structures after review',
      'Nominee/trustee functions after review',
      'Complex holding models by individual quote',
    ],
    process: [
      'Order and due-diligence review',
      'Coordination with the Registered Agent in Nevis',
      'Name and structure review',
      'Preparation of the formation documents',
      'Formation of the Nevis LLC',
      'Handover of the company data',
    ],
    hint: 'Not suitable for: retroactively defeating existing creditor rights, tax evasion, concealed beneficial owners or undocumented payment flows. Price plus government fees and Registered Agent costs.',
    tags: ['Nevis LLC', 'Asset protection', 'Offshore', 'International company formation', 'Nevis'],
  },
  'australische-pty-ltd-gruenden': {
    name: 'Form an Australian Pty Ltd',
    shortDesc: 'Formation of an Australian Proprietary Limited Company / Pty Ltd with ASIC registration, structure preparation and an optional business address in Sydney, Melbourne, Brisbane or Perth.',
    included: [
      'Pre-check of the planned Australian company structure',
      'Name and basic data review for the Pty Ltd',
      'Preparation of the ASIC company registration',
      'Structuring of Directors, Shareholders and Share Capital',
      'Support with written consents from officeholders and shareholders',
      'Coordination of the Registered Office / service address option (Sydney, Melbourne, Brisbane or Perth)',
      'Formation documentation and handover of the company documents',
      'Guidance on ACN, ABN, GST, TFN and ongoing ASIC obligations',
    ],
    notIncluded: [
      'Automatic provision of an Australian resident director',
      'ABN / Tax File Number / GST registration (available as a separate option)',
      'Registered Office / service address (available as a separate option)',
      'Official ASIC / register fees',
      'Tax advice in Australia or Germany',
      'Bookkeeping, GST returns or payroll',
      'Bank account opening',
      'Visa, residency or immigration advice',
    ],
    addons: [
      'Registered Office / Service Address in Sydney, Melbourne, Brisbane or Perth',
      'ABN support',
      'ABN + TFN/GST pre-check',
      'Resident-director / local-director solution after separate due-diligence review',
      'Bank account support on request',
      'Accounting / tax support on request',
      'Ongoing ASIC / company administration on request',
    ],
    process: [
      'Order and data submission',
      'Review of the director-residency requirements',
      'Pre-check of the company name',
      'Preparation of the formation documents',
      'Formation of the Pty Ltd with ASIC, issue of the ACN',
      'Handover of the company data',
    ],
    hint: 'An Australian Pty Ltd needs at least one director who lives in Australia. Taking on or arranging a resident/local director function does not happen automatically, only after a due-diligence, purpose and risk review. Price plus ASIC/register fees, address costs, external provider costs and add-ons.',
    tags: ['Pty Ltd', 'Australia', 'Australian Limited', 'Asia-Pacific', 'International company formation'],
  },
  'uk-limited-nominee-treuhandadministration': {
    name: 'UK Limited Nominee and Trustee Administration',
    shortDesc: 'Professional nominee and trustee administration for UK Limited structures — documented, compliance-oriented and fully transparent regarding beneficial owners.',
    priceLabel: 'From an individual quote after review',
    included: [
      'KYC/AML review and documentation of beneficial owners',
      'Nominee Shareholder / trustee administration after mandate review',
      'Nominee Director after case-by-case review',
      'Mandate, instruction and resolution documentation',
      'Coordination with UK Company Secretary and Registered Office',
      'Ongoing Companies House compliance and Annual Confirmation Statement',
    ],
    notIncluded: [
      'Anonymous or concealed company structures',
      'Concealment of beneficial owners (PSC)',
      'Tax evasion or circumvention of tax obligations',
      'Undocumented payment flows',
    ],
    addons: [
      'Ongoing bookkeeping and accounting',
      'Registered Office renewal',
      'Bank account and payment administration after separate review',
    ],
    process: [
      'Enquiry and initial structure description',
      'KYC/AML and compliance review',
      'Mandate acceptance and contract drafting',
      'Set-up of the nominee/trustee structure',
      'Ongoing administration and documentation',
    ],
    hint: 'This offer serves exclusively professional, documented company administration. A mandate is only accepted after a complete KYC and compliance review.',
    tags: ['UK Nominee', 'Trustee', 'UK Limited', 'Company administration'],
  },
  'internationale-nominee-treuhandadministration': {
    name: 'International Nominee and Trustee Administration',
    shortDesc: 'Cross-jurisdiction nominee, trustee and mandate administration for international company structures — e.g. Hong Kong, Ireland, Belize, Nevis, Cayman, Australia or New Zealand.',
    priceLabel: 'From €2,490 — individual quote after due diligence',
    included: [
      'International structure and jurisdiction review',
      'KYC/AML/sanctions and risk review of the parties involved',
      'Review and documentation of beneficial owners / UBO / PSC / RBO',
      'Review of tax residency, source of funds and business purpose',
      'Coordination with local Registered Agents and Company Secretaries',
      'Nominee Shareholder / trustee administration after mandate review',
      'Mandate, instruction and resolution documentation',
      'Ongoing compliance, register and renewal support',
    ],
    notIncluded: [
      'Anonymous or concealed company structures',
      'Concealment of beneficial owners',
      'Tax evasion or circumvention of tax obligations',
      'Concealed third-party payments or untraceable payment flows',
      'Delaying insolvency or prejudicing creditors',
    ],
    addons: [
      'Bank account and payment administration after separate review',
      'Multi-jurisdiction holding structures by individual quote',
    ],
    process: [
      'Enquiry and structure description',
      'International due-diligence review',
      'Structure and jurisdiction analysis',
      'Mandate acceptance after review',
      'Set-up of the international structure',
      'Ongoing compliance administration',
    ],
    hint: 'This offer is not an automatically orderable standard product. Final acceptance, structure approval and price confirmation are given exclusively after an individual due-diligence review. Nominee Director from €7,900/year, complex structures from €14,900/year.',
    tags: ['International nominee', 'Trustee', 'Asset protection', 'Holding', 'Multi-jurisdiction'],
  },
  'deutsche-treuhand-mandatsadministration': {
    name: 'German Trustee and Mandate Administration',
    shortDesc: 'Trustee service for German companies — a mandate is only accepted after a free pre-check of beneficial owners, purpose and background.',
    priceLabel: 'Pre-check free of charge — trustee activity €280/month (base fee)',
    included: [
      'Free pre-check of the corporate structure',
      'KYC/AML review of the beneficial owners',
      'Review of transparency-register, UBO and shareholding disclosures',
      'Review of tax residency, source of funds and intended use',
      'Risk review for management, shareholding or trustee functions',
      'Written mandate and instruction documentation',
      'Ongoing compliance and documentation administration',
      'Coordination with tax advisor, lawyer or notary as required',
    ],
    notIncluded: [
      'Anonymous or concealed company structures',
      'Concealment of beneficial owners',
      'Tax evasion or circumvention of tax obligations',
      'Concealed third-party payments or untraceable payment flows',
      'Delaying insolvency, prejudicing creditors or asset transfers',
      'Constructions where the actual purpose is not fully disclosed',
    ],
    addons: [
      'Digital account providers: Finom / bunq pre-check',
      'High-street banks: Deutsche Bank / Commerzbank / HVB',
      'Complex bank review with trustee/officer function',
      'Management, officer or special payment administration',
    ],
    process: [
      'Enquiry and initial structure description',
      'Free KYC/AML and compliance review',
      'Review of UBO, tax residency and source of funds',
      'Mandate acceptance and contract drafting after review',
      'Set-up of the trustee/mandate structure',
      'Ongoing compliance and documentation administration',
    ],
    hint: 'The €280/month is a monthly base fee for the corporate-officer trustee activity. Work beyond that scope is requested in advance and billed separately case by case. This offer expressly does not serve the covert "burial" of a company, extracting former officers from a problematic company, or concealing a situation on the brink of insolvency. If there are indications of impermissible use, no mandate will be taken on, or an ongoing one will be ended immediately. Not an automatically orderable standard product — the mandate is only accepted after a free pre-check.',
    tags: ['Trustee', 'Mandate administration', 'Germany', 'Compliance'],
  },
  'uk-limited-jahresadministration': {
    name: 'UK Limited Annual Administration',
    shortDesc: 'Ongoing administration of your UK Limited for 12 months: deadline monitoring, Companies House filings, Confirmation Statement, register-data review and UK compliance support.',
    priceLabel: 'From €399/year — Dormant, Active or Premium, depending on the variant',
    included: [
      'Review of the current Companies House data',
      'Deadline monitoring for the Confirmation Statement and Accounts',
      'Preparation and filing of the Confirmation Statement',
      'Review of Directors, PSCs, Shareholders and SIC code',
      'Review of Registered Office and Registered Email Address',
      'Support with simple Companies House changes',
      'Support with dormant accounts, where applicable',
      'Reminders for HMRC/Corporation Tax deadlines',
      'Annual compliance check',
    ],
    notIncluded: [
      'Tax advice',
      'Bookkeeping, complex annual accounts, VAT returns, PAYE/payroll',
      'Bank account opening',
      'Legal or tax structuring advice',
      'HMRC disputes',
      'Remediation of significantly overdue or already flagged companies',
    ],
    addons: [
      'Dormant Limited Administration',
      'Active Limited Administration',
      'Premium Limited Administration',
    ],
    process: [
      'Order and submission of the company data',
      'Review of the current Companies House status',
      'Clarification of Confirmation Statement and Accounts deadlines',
      'Ongoing deadline monitoring over 12 months',
      'Filing of the Confirmation Statement',
      'Annual compliance check',
    ],
    hint: 'The Companies House Authentication Code is not requested directly in the order process — after ordering, you will receive separate instructions for securely submitting it. The service runs for 12 months from acceptance of the order and does not renew automatically. All prices plus official fees and external costs.',
    tags: ['UK Limited', 'Annual administration', 'Companies House', 'Compliance'],
  },
  'geschaeftsadresse-pan-office': {
    name: 'Book a Business Address',
    shortDesc: 'Digital business address at over 100 locations worldwide — bookable instantly, with digital mail management. From 3 locations in one booking, the volume discount applies automatically.',
    priceLabel: 'From €29.00/month — directly at pan-office.de',
    included: [
      'Over 100 locations worldwide to choose from',
      'Digital mail management',
      'Bookable instantly, no lease agreement',
      'Volume discount from 3 locations',
      '2% EUROPAN bonus on every booking',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'This offer is booked directly at pan-office.de — current locations, prices and availability can always be viewed live there.',
    tags: ['Business address', 'PO box', 'pan-office'],
  },
  'europan-guthaben-aufladen': {
    name: 'Top Up EUROPAN Balance',
    shortDesc: 'Top up your EUROPAN balance directly — by credit card or bank transfer, in an amount of your choice. Redeemable network-wide, including here in the shop for the Doppel-Wums bonus.',
    priceLabel: 'Choose your amount — directly at europan.group',
    included: [
      'Instant credit on card payment',
      'Amount of your choice',
      'Redeemable network-wide (shop, pan-office.de and others)',
      'Prerequisite for the Doppel-Wums bonus',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'This offer is processed directly at europan.group.',
    tags: ['EUROPAN', 'Balance', 'Voucher'],
  },
  'linkcheck-plus': {
    name: 'LinkCheck Plus',
    shortDesc: 'Weekly automatic crawl of your website (up to 150 pages) with email alerts as soon as new broken internal or external links appear.',
    priceLabel: 'From €2.90/month — directly at kaputte-links.de',
    included: [
      'Weekly automatic crawl (up to 150 pages)',
      'Email alert for newly found broken links',
      'Full history of all checks',
      'Cancel monthly at any time',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'Requires an existing free kaputte-links.de registration. Upgrade directly at kaputte-links.de/plus.html.',
    tags: ['LinkCheck', 'Broken links', 'Monitoring', 'Plus'],
  },
  'pan21counter-plus': {
    name: 'PAN21counter Plus',
    shortDesc: 'Extended statistics for your free PAN21counter visitor counter: 365-day history, weekly email report, badge without PAN21 branding.',
    priceLabel: 'From €0.99/month — directly at pan21counter.de',
    included: [
      '365-day statistics history instead of 30 days',
      'Weekly email report',
      'Badge without PAN21counter branding',
      'Cancel monthly at any time',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'Requires an existing free PAN21counter account. Upgrade directly at pan21counter.de/plus.html.',
    tags: ['PAN21counter', 'Statistics', 'Web analytics', 'Plus'],
  },
  'site-ok-plus': {
    name: 'site-ok.de Plus',
    shortDesc: 'Uptime monitoring with email alerts: find out immediately when your website goes down — not only once a customer complains.',
    priceLabel: 'From €2.90/month — directly at site-ok.de',
    included: [
      'Email alert as soon as your website goes down',
      'Email confirmation once it is back online',
      'Extended history',
      'Cancel monthly at any time',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'Requires an existing free site-ok.de registration. Upgrade directly at site-ok.de/plus.html.',
    tags: ['site-ok', 'Uptime', 'Monitoring', 'Plus'],
  },
  'pagespeed-plus-abo': {
    name: 'PageSpeed Plus',
    shortDesc: 'Daily performance monitoring instead of a weekly single check — with email alerts as soon as your website\'s Google PageSpeed score drops significantly.',
    priceLabel: 'From €2.90/month — directly at pagespeed-plus.de',
    included: [
      'Daily performance monitoring',
      'Email alert on score deterioration',
      'Detailed score history',
      'Cancel monthly at any time',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'Requires an existing free pagespeed-plus.de registration. Upgrade directly at pagespeed-plus.de/plus.html.',
    tags: ['PageSpeed', 'Performance', 'Monitoring', 'Plus'],
  },
  'spam-abwehr-plus': {
    name: 'Spam-Abwehr Plus',
    shortDesc: 'Real-time API access to the shared spam blocklist for your own forms — also outside the PAN21 network, with a personal API key.',
    priceLabel: 'From €4.90/month — directly at spam-abwehr.de',
    included: [
      'Your own API key for real-time checks',
      'Up to 60 requests per minute',
      'Usable in any of your own forms',
      'Cancel monthly at any time',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'This offer is booked directly at spam-abwehr.de — the API key is emailed after payment.',
    tags: ['Spam protection', 'API', 'Form protection', 'Plus'],
  },
  'impressum-free-plus': {
    name: 'Impressum-Free Plus',
    shortDesc: 'Annual automatic reminder to review your legal notice (Impressum), plus notification of relevant legal changes — for your free-of-charge legal notice.',
    priceLabel: 'From €1.90/month — directly at impressum-free.de',
    included: [
      'Annual reminder to review the legal notice',
      'Notification of legal changes',
      'Your details stay saved for fast regeneration',
      'Cancel monthly at any time',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'This offer is booked directly at impressum-free.de.',
    tags: ['Legal notice', 'Compliance', 'Plus'],
  },
  'ipbx-telefonzentrale': {
    name: 'i-PBX Phone System with Extension',
    shortDesc: 'German landline number with a personal extension and a genuine 24-hour phone system — callers are greeted by name and automatically routed to you, reachable via app or desk phone.',
    priceLabel: 'From €4.90/month, with AI reception from €24.80/month — directly at i-pbx.eu',
    included: [
      'German landline number (Berlin or Frankfurt) with personal extension',
      'Choose your own number or automatic assignment',
      'Reachable via the free IRIS app or a desk phone',
      'Optional: 24h AI phone system — callers are greeted by name and automatically connected',
      'Ready to use instantly, no contract commitment',
    ],
    notIncluded: [],
    addons: [
      'AI reception assistant (company switchboard with name/department recognition)',
    ],
    process: [],
    hint: 'This offer is booked directly at i-pbx.eu — available numbers, prices and the AI option can be viewed live there.',
    tags: ['Phone system', 'Extension', 'Virtual office', 'i-pbx', 'AI reception'],
  },
  'webhosting-1euro-hosting': {
    name: 'WordPress Web Hosting',
    shortDesc: 'WordPress hosting from €1/month — cancel monthly, with a free subdomain or your own domain. Ideal as an add-on to a new business address or company formation.',
    priceLabel: 'From €1.00/month — directly at 1euro-hosting.de',
    included: [
      'WordPress hosting from €1/month',
      'Cancel monthly',
      'Free subdomain or your own domain from €9.90/year',
      'Basic (€3) and Pro (€9.90) without advertising',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'This offer is booked directly at 1euro-hosting.de.',
    tags: ['Hosting', 'WordPress', 'Web hosting'],
  },
  'pan21-vorzugsaktien': {
    name: 'Acquire PAN21 Preferred Shares',
    shortDesc: 'Take a stake in the international PAN21 network through preferred shares — attractive investment structures for investors, advisors and entrepreneurs.',
    priceLabel: 'Participation by agreement — directly at pan21.net',
    included: [
      'Access to a growing international network',
      'Preferred shares with attractive investment structures',
      'Ideal for investors, advisors and entrepreneurs',
      'Long-term, sustainable value',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'This offer is handled directly at pan21.net — current investment structures and terms can be viewed there.',
    tags: ['Preferred shares', 'Investment', 'PAN21 network'],
  },
  'finance-ads-bannerwerbung': {
    name: 'Finance-Ads Banner Advertising',
    shortDesc: 'Your banner ad runs for 30 days simultaneously across more than a dozen finance and business websites in the PAN21 network — footer, sidebar, or both in a combo package.',
    priceLabel: 'From €24 / 30 days — footer, sidebar or combo, directly at finance-ads.com',
    included: [
      'Footer banner (728×125 px) across the whole PAN21 network — €24',
      'Sidebar banner (160×600 px) in the right-hand sidebar — €29',
      'Combo package footer + sidebar, best value — €44 (recommended)',
      '30-day term, automatic activation after payment',
      'Visibility across more than a dozen finance and business websites at once',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'This offer is booked directly at finance-ads.com — the current network sites, banner formats and prices can always be viewed live there.',
    tags: ['Advertising', 'Banner', 'Finance advertising', 'Finance-Ads', 'Marketing'],
  },
  'series-llc-gruendung': {
    name: 'Formation of an American Series LLC',
    shortDesc: 'One master LLC, any number of series underneath it — each with its own liability shield. One-off formation from €49, annual administration from €19. Office, phone and internet options can be added directly during the order.',
    priceLabel: 'Formation from €49 · annual administration from €19 — directly at einfach-llc.de',
    included: [
      'Master LLC with any number of series underneath it',
      'Each series with its own liability shield (asset protection)',
      'Multiple members and managers possible',
      'Digital Operating Agreement included',
      'One-off formation from €49, annual administration from €19',
      'Optional add-ons at order time: US office address, US phone number, web hosting/email',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'This offer is formed directly at einfach-llc.de. During the order process, office, phone and internet options (US business address, US phone number with automatic forwarding, website/email at 10com.net) can conveniently be added.',
    tags: ['Series LLC', 'USA', 'Company formation', 'Wyoming'],
  },
  'madagascar-start': {
    name: 'Madagascar Start – SARLU / SARL',
    shortDesc: 'Entry-level package for an uncomplicated start in Madagascar: company formation, basic German-language advice and a business address for 12 months.',
    priceLabel: 'from €2,990 (SARLU) / €3,290 (SARL)',
    included: [
      'Formation of a SARLU (single shareholder) or SARL (multiple shareholders, +€300)',
      'Basic German-language advice & document review',
      'Business address for 12 months',
      'Support through standard registration',
      'Digital handover of the company documents',
    ],
    notIncluded: ['Bank account support', 'Bookkeeping', 'Compliance support', 'Official fees'],
    addons: ['Bank account support', 'Bookkeeping & tax', 'Basic compliance service'],
    process: ['Enquiry & initial call', 'Document review', 'SARLU/SARL formation on-site in Nosy Be', 'Handover of the company documents'],
    hint: 'On-site in Nosy Be, German-speaking support. Official fees, certifications and translations are billed separately.',
    tags: ['Madagascar', 'SARLU', 'SARL', 'Company formation', 'Africa'],
  },
  'madagascar-business-sarlu': {
    name: 'Madagascar Business – SARLU',
    shortDesc: 'Formation with bank account support and an initial compliance review — for a professional business start as a single shareholder.',
    included: [
      'Formation of a SARLU',
      'Business address for 12 months',
      'Bank account support',
      'Mail receipt & digital forwarding',
      'Initial compliance review',
      'German-speaking support during the formation phase',
    ],
    notIncluded: ['Ongoing bookkeeping', 'Tax returns', 'Official fees'],
    addons: ['Ongoing bookkeeping & tax', 'Annual compliance packages (Care Basic/Plus)'],
    process: ['Enquiry & initial call', 'SARLU formation', 'Bank account preparation', 'Initial compliance review'],
    hint: 'The decision on opening an account rests solely with the respective bank and cannot be guaranteed.',
    tags: ['Madagascar', 'SARLU', 'Company formation', 'Bank account', 'Africa'],
  },
  'madagascar-business-sarl': {
    name: 'Madagascar Business – SARL',
    shortDesc: 'Formation with bank account support and an initial compliance review — for multiple shareholders and joint investments.',
    included: [
      'Formation of a SARL (multiple shareholders)',
      'Business address for 12 months',
      'Bank account support',
      'Mail receipt & digital forwarding',
      'Initial compliance review',
      'German-speaking support during the formation phase',
    ],
    notIncluded: ['Ongoing bookkeeping', 'Tax returns', 'Official fees'],
    addons: ['Ongoing bookkeeping & tax', 'Annual compliance packages (Care Basic/Plus)'],
    process: ['Enquiry & initial call', 'SARL formation', 'Bank account preparation', 'Initial compliance review'],
    hint: 'The decision on opening an account rests solely with the respective bank and cannot be guaranteed.',
    tags: ['Madagascar', 'SARL', 'Company formation', 'Bank account', 'Africa'],
  },
  'madagascar-business-complete-sarlu': {
    name: 'Madagascar Business Complete – SARLU',
    shortDesc: 'Comprehensive package with a company secretary, basic compliance service and administration hours — full, continuous support.',
    included: [
      'Formation of a SARLU',
      'Business address for 12 months',
      'Bank account + digital mail forwarding',
      'Administrative company secretary for 12 months',
      'Annual basic compliance service',
      'Up to 6 hours of company administration',
      'German-speaking premium support',
    ],
    notIncluded: ['Ongoing bookkeeping', 'Investor visa', 'Official fees'],
    addons: ['Investor visa / residence card (see Investor Complete)', 'Ongoing bookkeeping & tax'],
    process: ['Enquiry & initial call', 'SARLU formation', 'Set-up of compliance & administration', 'Ongoing premium support'],
    hint: 'On-site in Nosy Be, German-speaking support. Official fees billed separately.',
    tags: ['Madagascar', 'SARLU', 'Company formation', 'Compliance', 'Africa'],
  },
  'madagascar-investor-complete-sarlu': {
    name: 'Madagascar Investor Complete – SARLU',
    shortDesc: 'Business Complete plus support with the investor visa/residence card and an initial relocation consultation — for a complete move to Madagascar.',
    included: [
      'All services of the Business Complete SARLU package',
      'Support with investor visa / residence card',
      'Preparation & review of the standard documents',
      'Initial relocation consultation',
      'Coordination of appointments and procedural steps',
    ],
    notIncluded: ['Official visa and residence fees'],
    addons: ['Housing search, bank, phone, authorities (full relocation service)'],
    process: ['Enquiry & initial call', 'SARLU formation', 'Visa preparation', 'Relocation support'],
    hint: 'Official visa and residence fees are not included.',
    tags: ['Madagascar', 'SARLU', 'Investor visa', 'Relocation', 'Africa'],
  },
  'madagascar-investor-complete-sarl': {
    name: 'Madagascar Investor Complete – SARL',
    shortDesc: 'Business Complete plus support with the investor visa/residence card and an initial relocation consultation — for multiple shareholders.',
    included: [
      'All services of the Business Complete SARL package',
      'Support with investor visa / residence card',
      'Initial relocation consultation & appointment coordination',
    ],
    notIncluded: ['Official visa and residence fees'],
    addons: ['Housing search, bank, phone, authorities (full relocation service)'],
    process: ['Enquiry & initial call', 'SARL formation', 'Visa preparation', 'Relocation support'],
    hint: 'Official visa and residence fees are not included.',
    tags: ['Madagascar', 'SARL', 'Investor visa', 'Relocation', 'Africa'],
  },
  'madagascar-holding-start': {
    name: 'Madagascar Holding Start – SARLU / SARL',
    shortDesc: 'Formation with an extended holding and shareholding purpose, including an initial holding consultation and review of existing shareholdings.',
    included: [
      'SARLU/SARL formation with extended holding & shareholding purpose',
      'German-language initial holding consultation & structure intake',
      'Review of the shareholding overview (up to three shareholdings)',
      'Business address for 12 months',
      'Bank account support',
      'Initial compliance review & coordination of the local tax review',
    ],
    notIncluded: [
      'Transfer/contribution of existing shares',
      'Business valuations',
      'Notarial services',
      'Foreign legal & tax advice',
      'Taxes, levies, register costs',
    ],
    addons: ['Ongoing holding & shareholding administration'],
    process: ['Enquiry & initial call', 'Initial holding consultation', 'SARLU/SARL formation', 'Compliance coordination'],
    hint: 'For international investors with existing or planned shareholding structures.',
    tags: ['Madagascar', 'Holding', 'Shareholding', 'Company formation', 'Africa'],
  },
  'madagascar-care-basic': {
    name: 'Madagascar Care Basic',
    shortDesc: 'Annual support package from the second year onward: business address, mail receipt and basic compliance service.',
    priceLabel: '€1,290 / year',
    included: [
      'Business address',
      'Mail receipt & digitisation',
      'Basic compliance service',
      'Annual review of the core company data',
      'Deadline reminders',
    ],
    notIncluded: ['Bookkeeping', 'Annual accounts', 'Tax returns'],
    addons: ['Bookkeeping & tax', 'Upgrade to Care Plus'],
    process: ['Order', 'Activation of the annual support', 'Ongoing deadline monitoring'],
    hint: 'Bookkeeping, annual accounts, tax returns and official fees are billed separately.',
    tags: ['Madagascar', 'Compliance', 'Annual support', 'Africa'],
  },
  'madagascar-care-plus': {
    name: 'Madagascar Care Plus',
    shortDesc: 'Extended annual support package with a virtual office, company secretary and up to 6 hours of company administration.',
    priceLabel: '€1,990 / year',
    included: [
      'Virtual office',
      'Administrative company secretary',
      'Basic compliance service',
      'Mail receipt & digitisation',
      'Up to 6 hours of company administration',
      'Ongoing German-speaking support',
    ],
    notIncluded: ['Bookkeeping', 'Annual accounts', 'Tax returns', 'Official fees'],
    addons: ['Ongoing bookkeeping & tax'],
    process: ['Order', 'Activation of the annual support', 'Ongoing German-speaking support'],
    hint: 'Bookkeeping, annual accounts, tax returns and official fees are billed separately.',
    tags: ['Madagascar', 'Compliance', 'Annual support', 'Virtual office', 'Africa'],
  },
  'madagascar-exit-basic': {
    name: 'Madagascar Exit Basic',
    shortDesc: 'Orderly voluntary wind-up for a solvent SARLU or simple SARL — from the initial review through to RCCM deregistration.',
    included: [
      'For solvent SARLU or simple SARL, orderly voluntary wind-up',
      'Initial review of liquidation eligibility & compilation of documents',
      'Preparation & coordination of the shareholder resolution',
      'Coordination of the liquidator appointment & publication/register steps',
      'Checklist for creditors, contracts, employees, taxes, social contributions, bank account',
      'Coordination of closing documents & RCCM deregistration',
    ],
    notIncluded: ['Accountant, tax advisor, lawyer, publication, court and other third-party costs'],
    addons: ['Extended liquidation with employees/multiple creditors (individual quote)'],
    process: ['Enquiry & initial review', 'Shareholder resolution', 'Liquidator appointment', 'RCCM deregistration'],
    hint: 'Requires that the company can meet its obligations in an orderly manner.',
    tags: ['Madagascar', 'Liquidation', 'Company wind-up', 'Africa'],
  },
}

export const CATEGORY_LABELS_EN: Record<string, string> = {
  'alle': 'All',
  'PAN21-Netzwerk': '⭐ PAN21 Network',
  'Deutschland': '🇩🇪 Germany',
  'UK / Großbritannien': '🇬🇧 UK',
  'USA': '🇺🇸 USA',
  'Hong Kong': '🇭🇰 Hong Kong',
  'Irland': '🇮🇪 Ireland',
  'Neuseeland': '🇳🇿 New Zealand',
  'Australien': '🇦🇺 Australia',
  'Nevis': '🏝️ Nevis',
  'Belize': '🏝️ Belize',
  'International': '🌐 International',
  'Madagaskar': '🇲🇬 Madagascar',
}

// Plain-text category name (no flag/emoji prefix) — used where the German
// site prints `product.category` directly, e.g. the product card and the
// product-detail breadcrumb.
export const CATEGORY_NAME_EN: Record<string, string> = {
  'PAN21-Netzwerk': 'PAN21 Network',
  'Deutschland': 'Germany',
  'UK / Großbritannien': 'UK / United Kingdom',
  'USA': 'USA',
  'Hong Kong': 'Hong Kong',
  'Irland': 'Ireland',
  'Neuseeland': 'New Zealand',
  'Australien': 'Australia',
  'Nevis': 'Nevis',
  'Belize': 'Belize',
  'International': 'International',
  'Madagaskar': 'Madagascar',
}

export const CATEGORIES_EN = [
  { id: 'alle', label: 'All' },
  { id: 'PAN21-Netzwerk', label: '⭐ PAN21 Network' },
  { id: 'Deutschland', label: '🇩🇪 Germany' },
  { id: 'UK / Großbritannien', label: '🇬🇧 UK' },
  { id: 'USA', label: '🇺🇸 USA' },
  { id: 'Hong Kong', label: '🇭🇰 Hong Kong' },
  { id: 'Irland', label: '🇮🇪 Ireland' },
  { id: 'Neuseeland', label: '🇳🇿 New Zealand' },
  { id: 'Australien', label: '🇦🇺 Australia' },
  { id: 'Nevis', label: '🏝️ Nevis' },
  { id: 'Belize', label: '🏝️ Belize' },
  { id: 'International', label: '🌐 International' },
  { id: 'Madagaskar', label: '🇲🇬 Madagascar' },
]

// Merges the German PRODUCTS (source of truth for slug/sku/price/image/flag/
// category id/inquiry/externalUrl) with the English copy above. Falls back
// to the German product untouched if a translation is ever missing, so a
// newly added German product never breaks the English build — it just
// shows German text until translated.
export function getProductsEn(): Product[] {
  return PRODUCTS.map((p): Product => {
    const t = PRODUCT_TRANSLATIONS[p.slug]
    if (!t) return p
    return {
      ...p,
      name: t.name,
      shortDesc: t.shortDesc,
      priceLabel: t.priceLabel ?? p.priceLabel,
      included: t.included,
      notIncluded: t.notIncluded,
      addons: t.addons,
      process: t.process,
      hint: t.hint,
      tags: t.tags,
    }
  })
}

export const PRODUCTS_EN: Product[] = getProductsEn()
