export type Product = {
  slug: string
  sku: string
  name: string
  shortDesc: string
  price: number | null  // null = Anfrage-Produkt ODER externalUrl-Angebot
  priceLabel?: string
  category: string
  flag: string
  image: string
  heroImage?: string  // optionales, hochwertigeres Bild für die Produkt-Detailseite (falls vorhanden)
  included: string[]
  notIncluded: string[]
  addons: string[]
  process: string[]
  hint: string
  inquiry?: boolean  // true = Kontaktformular statt Warenkorb
  externalUrl?: string  // gesetzt = Karte verlinkt direkt auf Partnerseite, kein interner Checkout
  tags: string[]
}

export const PRODUCTS: Product[] = [
  {
    slug: 'deutsche-ug-gruendung',
    sku: 'EUROPAN-DE-UG-001',
    name: 'Deutsche UG-Gründung',
    shortDesc: 'Gründung einer deutschen Unternehmergesellschaft (haftungsbeschränkt) nach Musterprotokoll – inklusive Vorbereitung der Gründungsdaten, notarieller Gründung und Handelsregistereintragung.',
    price: 698,
    category: 'Deutschland',
    flag: '🇩🇪',
    image: '/products/deutschland-300x300.png',
    heroImage: '/hero/deutschland-ug.jpg',
    included: [
      'Vorbereitung der Gründungsdaten',
      'Abstimmung des gewünschten Firmennamens',
      'Gründung nach Musterprotokoll',
      'Vorbereitung der notariellen Gründung',
      'Handelsregisteranmeldung',
      'Begleitung bis zur Eintragung',
      'Grundpaket mit einem Geschäftsführer und einem Gesellschafter',
    ],
    notIncluded: [
      'Bankkontoeröffnung',
      'Gewerbeanmeldung',
      'Laufende Buchhaltung',
      'Steuerliche Beratung',
      'Individuelle Satzung außerhalb des Musterprotokolls',
      'Laufende Geschäftsadresse, sofern nicht gesondert gebucht',
    ],
    addons: [
      'Ergänzende Geschäftsadresse / Postservice',
      'Verwaltungs- und Geschäftsführungsstrukturen nach Prüfung',
    ],
    process: [
      'Bestellung des Gründungspakets',
      'Übermittlung der erforderlichen Daten',
      'Prüfung und Abstimmung des gewünschten Firmennamens',
      'Vorbereitung der Gründungsunterlagen',
      'Notarielle Gründung und Handelsregisteranmeldung',
      'Eintragung der Gesellschaft',
    ],
    hint: 'Das Stammkapital der UG beträgt mindestens 1,00 EUR. Das Paket orientiert sich an einer Gründung mit einem Stammkapital von 1.000,00 EUR.',
    tags: ['UG', 'Unternehmergesellschaft', 'Deutschland', 'Firmengründung', 'haftungsbeschränkt'],
  },
  {
    slug: 'deutsche-gmbh-gruendung',
    sku: 'EUROPAN-DE-GMBH-001',
    name: 'Deutsche GmbH-Gründung',
    shortDesc: 'Gründung einer deutschen GmbH nach Musterprotokoll – inklusive Vorbereitung der Gründungsdaten, notarieller Gründung und Handelsregistereintragung.',
    price: 1298,
    category: 'Deutschland',
    flag: '🇩🇪',
    image: '/products/deutschland-300x300.png',
    heroImage: '/hero/deutschland-gmbh.jpg',
    included: [
      'Vorbereitung der Gründungsdaten',
      'Abstimmung des gewünschten Firmennamens',
      'Gründung nach Musterprotokoll',
      'Vorbereitung der notariellen Gründung',
      'Handelsregisteranmeldung',
      'Begleitung bis zur Eintragung',
      'Grundpaket mit einem Geschäftsführer und einem Gesellschafter',
    ],
    notIncluded: [
      'Bankkontoeröffnung',
      'Gewerbeanmeldung',
      'Laufende Buchhaltung',
      'Steuerliche Beratung',
      'Individuelle Satzung außerhalb des Musterprotokolls',
      'Laufende Geschäftsadresse, sofern nicht gesondert gebucht',
    ],
    addons: [
      'Ergänzende Office- oder Geschäftsadressen',
      'Postservice-Leistungen',
      'Verwaltungs- und Strukturierungsoptionen nach Prüfung',
    ],
    process: [
      'Bestellung des Gründungspakets',
      'Übermittlung der erforderlichen Daten',
      'Prüfung und Abstimmung des gewünschten Firmennamens',
      'Vorbereitung der Gründungsunterlagen',
      'Notarielle Gründung und Handelsregisteranmeldung',
      'Eintragung der Gesellschaft',
    ],
    hint: 'Das Stammkapital der GmbH beträgt grundsätzlich 25.000,00 EUR. Davon muss vor der Eintragung mindestens die gesetzlich erforderliche Einzahlung geleistet werden.',
    tags: ['GmbH', 'Deutschland', 'Firmengründung', 'Kapitalgesellschaft'],
  },
  {
    slug: 'englische-limited-gruenden',
    sku: 'EUROPAN-UK-LTD-001',
    name: 'Englische Limited gründen',
    shortDesc: 'Professionelle Gründung einer englischen Limited Company mit Vorbereitung der Gründungsdaten, Companies-House-Eintragung und verständlicher Begleitung.',
    price: 299,
    category: 'UK / Großbritannien',
    flag: '🇬🇧',
    image: '/products/uk-300x300.png',
    heroImage: '/hero/uk.jpg',
    included: [
      'Vorprüfung der gewünschten Firmierung',
      'Vorbereitung der Gründungsdaten',
      'Gründung der UK Limited Company',
      'Eintragung bei Companies House',
      'Bereitstellung der Gründungsunterlagen',
      'Hinweise zu Director, Shareholder und PSC',
      'Hinweise zu den laufenden Registerpflichten',
      'Übergabe der relevanten Gesellschaftsdaten nach Eintragung',
    ],
    notIncluded: [
      'Registered Office / Serviceadresse in UK',
      'Steuerliche Beratung',
      'Laufende Buchhaltung und Compliance-Betreuung',
      'Bankkontoeröffnung',
      'Fintech- oder Payment-Anbieter-Eröffnung',
      'Apostillen, Beglaubigungen oder Übersetzungen',
    ],
    addons: [
      'Registered Office / Serviceadresse in UK',
      'Unterstützung bei Änderungen bestehender UK-Gesellschaften',
      'Name Change einer bestehenden Limited',
      'Share Transfer / Gesellschafterwechsel',
      'Vorbereitung für Bank-, Fintech- oder Payment-Anbieter',
      'Laufender Compliance- und Erinnerungsservice',
    ],
    process: [
      'Bestellung und Datenübermittlung',
      'Vorprüfung der gewünschten Firmierung',
      'Vorbereitung der Gründungsunterlagen',
      'Eintragung bei Companies House',
      'Übergabe der Gesellschaftsdaten',
    ],
    hint: 'Seit dem 18. November 2025 ist die Identitätsverifikation für Directors und PSCs rechtlich relevant. Steuerliche Pflichten bei Wohnsitz in Deutschland oder Österreich müssen gesondert geprüft werden.',
    tags: ['UK Ltd', 'Limited', 'Englische Limited', 'Großbritannien', 'Internationale Firmengründung'],
  },
  {
    slug: 'amerikanische-llc-gruenden',
    sku: 'EUROPAN-US-LLC-001',
    name: 'Amerikanische LLC gründen',
    shortDesc: 'Professionelle Vorbereitung und Begleitung bei der Gründung einer amerikanischen LLC für internationale Unternehmer, digitale Geschäftsmodelle und projektbezogene US-Strukturen.',
    price: 399,
    category: 'USA',
    flag: '🇺🇸',
    image: '/products/usa-300x300.png',
    heroImage: '/hero/usa.jpg',
    included: [
      'Vorprüfung der gewünschten Firmierung',
      'Grundlegende Einordnung geeigneter US-Bundesstaaten',
      'Vorbereitung der Gründungsdaten',
      'Begleitung der LLC-Gründung im gewählten Bundesstaat',
      'Hinweise zu Member, Manager und Operating Agreement',
      'Hinweise zum Registered Agent',
      'Grundlegende Hinweise zum EIN-Thema',
      'Übergabe der relevanten Gesellschaftsdaten nach Gründung',
    ],
    notIncluded: [
      'Offizielle State Filing Fees',
      'Registered Agent Gebühren',
      'EIN-Antrag (als gesonderte Zusatzleistung verfügbar)',
      'Steuerliche Beratung',
      'Laufende Buchhaltung und Compliance-Betreuung',
      'Bankkontoeröffnung',
    ],
    addons: [
      'Registered Agent im gewählten Bundesstaat',
      'Operating Agreement',
      'EIN-Unterstützung für internationale Antragsteller',
      'US-Adresse oder Mail Forwarding',
      'Vorbereitung für Bank-, Fintech- oder Payment-Anbieter',
      'Apostille oder beglaubigte Gründungsunterlagen',
    ],
    process: [
      'Bestellung und Datenübermittlung',
      'Auswahl des geeigneten Bundesstaats',
      'Vorprüfung der Firmierung',
      'Vorbereitung der Gründungsunterlagen',
      'LLC-Gründung im gewählten Bundesstaat',
      'Übergabe der Gesellschaftsdaten',
    ],
    hint: 'Die Kosten, Pflichten und sinnvolle Gestaltung hängen stark vom gewählten Bundesstaat ab. State Filing Fees und Registered Agent Gebühren sind nicht im Basispreis enthalten.',
    tags: ['US LLC', 'LLC', 'USA', 'Amerikanische LLC', 'Internationale Firmengründung'],
  },
  {
    slug: 'hong-kong-limited-gruenden',
    sku: 'EUROPAN-HK-LTD-001',
    name: 'Hong Kong Limited gründen',
    shortDesc: 'Professionelle Gründung einer Hong Kong Limited mit Registered Office und Company Secretary. Geeignet für Asien-Geschäft, E-Commerce, Handel und digitale Geschäftsmodelle.',
    price: 899,
    category: 'Hong Kong',
    flag: '🇭🇰',
    image: '/products/hngkong-300x300.png',
    heroImage: '/hero/hongkong.jpg',
    included: [
      'Vorprüfung der gewünschten Firmierung',
      'Vorbereitung der Gründungsdaten',
      'Gründung einer Hong Kong Limited',
      'Registered Office in Hong Kong für den Startzeitraum',
      'Company Secretary in Hong Kong für den Startzeitraum',
      'Hinweise zu Director, Shareholder und Company Secretary',
      'Grundlegende Hinweise zur Business Registration',
      'Übergabe der relevanten Gesellschaftsdaten nach Gründung',
    ],
    notIncluded: [
      'Offizielle Behördengebühren (soweit separat berechnet)',
      'Business Registration Fee und Levy',
      'Steuerliche Beratung',
      'Laufende Buchhaltung, Audit oder Accounting Services',
      'Bankkontoeröffnung',
      'Fintech- oder Payment-Anbieter-Eröffnung',
      'Apostillen, Beglaubigungen oder Übersetzungen',
    ],
    addons: [
      'Verlängerung Registered Office',
      'Verlängerung Company Secretary',
      'Business-Registration-Verlängerung',
      'Accounting- und Audit-Vorbereitung',
      'Unterstützung bei Bank-, Fintech- oder Payment-Anbieter-Vorbereitung',
      'Laufender Compliance- und Erinnerungsservice',
    ],
    process: [
      'Bestellung und Datenübermittlung',
      'Vorprüfung der Firmierung',
      'Vorbereitung der Gründungsunterlagen',
      'Gründung der Hong Kong Limited',
      'Einrichtung von Registered Office und Company Secretary',
      'Übergabe der Gesellschaftsdaten',
    ],
    hint: 'Bankkonto, Fintech-Zugang oder Payment-Anbieter können nicht garantiert werden. Die Akzeptanz durch Banken hängt von Geschäftsmodell, Dokumentation und Compliance-Prüfung des jeweiligen Anbieters ab.',
    tags: ['Hong Kong Limited', 'HK Ltd', 'Asien', 'Internationale Firmengründung'],
  },
  {
    slug: 'irische-limited-gruenden',
    sku: 'EUROPAN-IE-LTD-001',
    name: 'Irische Limited gründen',
    shortDesc: 'Professionelle Vorbereitung und Begleitung bei der Gründung einer irischen Limited Company. Geeignet für EU-nahe Projektstrukturen und internationale Unternehmer.',
    price: 1199,
    category: 'Irland',
    flag: '🇮🇪',
    image: '/products/irland-300x300.png',
    heroImage: '/hero/irland.jpg',
    included: [
      'Vorprüfung der gewünschten Firmierung',
      'Grundlegende Prüfung, ob eine irische LTD sinnvoll erscheint',
      'Einordnung der Director- und EEA-Resident-Director-Thematik',
      'Vorbereitung der Gründungsdaten',
      'Begleitung der irischen LTD-Gründung',
      'Hinweise zu Director, Shareholder und Company Secretary',
      'Hinweise zu Beneficial Ownership und RBO-Thematik',
      'Übergabe der relevanten Gesellschaftsdaten nach Gründung',
    ],
    notIncluded: [
      'Irischer Resident Director',
      'Bond oder Ersatzlösungen für fehlenden EEA-Resident-Director',
      'Registered Office (soweit nicht separat vereinbart)',
      'Company Secretary (soweit nicht separat vereinbart)',
      'Steuerliche Beratung',
      'Laufende Buchhaltung, Accounting, Audit',
      'Bankkontoeröffnung',
    ],
    addons: [
      'Registered Office in Irland',
      'Company Secretary',
      'Unterstützung bei RBO-/Beneficial-Owner-Themen',
      'Revenue-/Tax-Registration-Vorbereitung',
      'Accounting- und Compliance-Vorbereitung',
      'Laufender Compliance- und Erinnerungsservice',
    ],
    process: [
      'Bestellung und Datenübermittlung',
      'Grundlegende Prüfung der Struktur und Director-Anforderungen',
      'Vorprüfung der Firmierung',
      'Vorbereitung der Gründungsunterlagen',
      'Begleitung der irischen LTD-Gründung',
      'Übergabe der Gesellschaftsdaten',
    ],
    hint: 'Die irische LTD ist eine seriöse EU-Gesellschaft mit strengen Register- und Compliance-Anforderungen. Director-Themen, Identitätsnachweise und wirtschaftlich Berechtigte müssen sorgfältig geprüft werden.',
    tags: ['Irish LTD', 'Irische Limited', 'EU Gesellschaft', 'Irland', 'Internationale Firmengründung'],
  },
  {
    slug: 'neuseelaendische-limited-gruenden',
    sku: 'EUROPAN-NZ-LTD-001',
    name: 'Neuseeländische Limited gründen',
    shortDesc: 'Professionelle Vorbereitung und Begleitung bei der Gründung einer neuseeländischen Limited Company mit lokaler Director-/Adressstruktur für den Startzeitraum.',
    price: 2999,
    category: 'Neuseeland',
    flag: '🇳🇿',
    image: '/products/nz-300x300.png',
    heroImage: '/hero/neuseeland.jpg',
    included: [
      'Vorprüfung der gewünschten Firmierung',
      'Grundlegende Prüfung, ob eine neuseeländische Ltd sinnvoll erscheint',
      'Einordnung der Director-Residency-Anforderungen',
      'Vorbereitung der Gründungsdaten',
      'Begleitung der neuseeländischen Ltd-Gründung',
      'Lokale Director-/Adressstruktur für den Startzeitraum (nach Prüfung)',
      'Hinweise zu Director, Shareholder und Shares',
      'Hinweise zu Registered Office, Serviceadresse und Kommunikationsadresse',
      'Übergabe der relevanten Gesellschaftsdaten nach Gründung',
    ],
    notIncluded: [
      'Regulierte Finanzdienstleistungen',
      'Bank-, Investment- oder erlaubnispflichtige Tätigkeiten',
      'Dauerhafte Director-/Adressleistungen über den Startzeitraum hinaus',
      'Nominee-Strukturen ohne wirtschaftliche Transparenz',
      'Offizielle Registergebühren (soweit separat berechnet)',
      'Steuerliche Beratung',
      'Laufende Buchhaltung und Accounting',
      'Bankkontoeröffnung',
    ],
    addons: [
      'Verlängerung lokaler Director-/Adressstruktur',
      'Registered Office in Neuseeland',
      'Inland-Revenue-/Tax-Registration-Vorbereitung',
      'Accounting- und Compliance-Vorbereitung',
      'Laufender Compliance- und Erinnerungsservice',
      'Unterstützung bei Bank-, Fintech- oder Payment-Anbieter-Vorbereitung',
    ],
    process: [
      'Bestellung und Datenübermittlung',
      'Prüfung der Director-Residency-Anforderungen',
      'Vorprüfung der Firmierung',
      'Vorbereitung der Gründungsunterlagen',
      'Begleitung der NZ Ltd-Gründung',
      'Übergabe der Gesellschaftsdaten',
    ],
    hint: 'Die Annahme dieses Auftrags steht unter Prüfvorbehalt. Die Director-Residency-Anforderung sollte nicht unterschätzt werden. Nicht jeder internationale Kunde kann ohne passende lokale Director-Struktur eine neuseeländische Gesellschaft führen.',
    tags: ['NZ Ltd', 'Neuseeländische Limited', 'New Zealand Limited', 'Neuseeland', 'Internationale Firmengründung'],
  },
  {
    slug: 'belize-llc-gruenden',
    sku: 'EUROPAN-BZ-LLC-001',
    name: 'Belize LLC gründen – Asset Protection Company Formation',
    shortDesc: 'Gründung einer Belize LLC für internationale Holding-, Vermögensverwaltungs- und Asset-Protection-Strukturen – mit Registered Agent, Due-Diligence-Prüfung und klarer Compliance-Abgrenzung.',
    price: 2990,
    category: 'Belize',
    flag: '🏝️',
    image: '/products/belize-300x300.png',
    heroImage: '/hero/belize.jpg',
    included: [
      'Vorprüfung der geplanten Belize-LLC-Struktur',
      'Namens- und Strukturprüfung',
      'Koordination mit Registered Agent / Registered Office',
      'Vorbereitung der Gründungsdaten und Mitgliederstruktur',
      'Einbindung von Operating Agreement / interner Struktur nach Bedarf',
      'Gründungsdokumentation und Übergabe der Gesellschaftsunterlagen',
      'Hinweise zu Renewal, Good Standing, Accounting Records und laufender Administration',
    ],
    notIncluded: [
      'Nachträgliche Entziehung von Vermögen gegenüber bestehenden Gläubigern',
      'Bankkontoeröffnung (nur nach gesonderter Prüfung)',
      'Laufende Administration, Nominee-/Treuhandfunktionen (separat geprüft)',
      'Komplexe Holdingmodelle (separat geprüft)',
      'Steuerliche Beratung',
    ],
    addons: [
      'Digitale Bank / Fintech-Vorprüfung',
      'Internationale Banklösung-Vorprüfung',
      'Komplexe Bankprüfung / Hochrisikoprofil',
      'Standard-Renewal & Good-Standing-Betreuung (jährlich)',
      'Premium-Administration mit Compliance-Betreuung (jährlich)',
      'Erweiterte Asset-Protection-/Holding-Struktur auf Anfrage',
    ],
    process: [
      'Bestellung und Due-Diligence-Prüfung',
      'Koordination mit Registered Agent in Belize',
      'Namens- und Strukturprüfung',
      'Vorbereitung der Gründungsunterlagen',
      'Gründung der Belize LLC',
      'Übergabe der Gesellschaftsdaten',
    ],
    hint: 'Asset Protection bedeutet nicht Anspruchsvereitelung. Nicht geeignet für Steuerhinterziehung, Gläubigerbenachteiligung, Insolvenzmissbrauch, verdeckte wirtschaftlich Berechtigte oder nachträgliche Vermögensverschiebung. Preis zzgl. staatlicher Gebühren, Registered-Agent-/Registered-Office-Kosten und Optionen.',
    tags: ['Belize LLC', 'Asset Protection', 'Holding', 'Internationale Firmengründung', 'Belize'],
  },
  {
    slug: 'nevis-llc-gruenden',
    sku: 'EUROPAN-NEVIS-LLC-001',
    name: 'Nevis LLC gründen',
    shortDesc: 'Gründung einer Nevis LLC als Premium-Struktur für internationale Asset Protection, Holding- und Vermögensverwaltungsmodelle – nur mit Due Diligence und klarer Zweckprüfung.',
    price: 3490,
    category: 'Nevis',
    flag: '🏝️',
    image: '/products/nevis-300x300.png',
    heroImage: '/hero/nevis.jpg',
    included: [
      'Vorprüfung der Nevis-LLC-Struktur',
      'Koordination mit lizenziertem Registered Agent in Nevis',
      'Namens- und Strukturprüfung',
      'Vorbereitung von Articles of Organization und Operating Agreement-Struktur',
      'Einrichtung der Mitglieder- und Managerstruktur',
      'Gründungsdokumentation und Übergabe der Gesellschaftsunterlagen',
      'Hinweise zu Annual Renewal, Good Standing und laufender Administration',
    ],
    notIncluded: [
      'Staatliche Gebühren',
      'Registered-Agent-/Registered-Office-Kosten',
      'Bankkontoeröffnung',
      'Komplexe Asset-Protection-Strukturen (separat zu prüfen)',
      'Nominee-/Treuhandfunktionen (separat zu prüfen)',
      'Steuerliche Beratung',
    ],
    addons: [
      'Bankkonto-Vorbereitung nach gesonderter Prüfung',
      'Besondere Asset-Protection-Strukturen nach Prüfung',
      'Nominee-/Treuhandfunktionen nach Prüfung',
      'Komplexe Holdingmodelle nach individuellem Angebot',
    ],
    process: [
      'Bestellung und Due-Diligence-Prüfung',
      'Koordination mit Registered Agent in Nevis',
      'Namens- und Strukturprüfung',
      'Vorbereitung der Gründungsunterlagen',
      'Gründung der Nevis LLC',
      'Übergabe der Gesellschaftsdaten',
    ],
    hint: 'Nicht geeignet für: nachträgliche Vereitelung bestehender Gläubigerrechte, Steuerhinterziehung, verschleierte wirtschaftlich Berechtigte oder nicht dokumentierte Zahlungsflüsse. Preis zuzüglich staatlicher Gebühren und Registered-Agent-Kosten.',
    tags: ['Nevis LLC', 'Asset Protection', 'Offshore', 'Internationale Firmengründung', 'Nevis'],
  },
  {
    slug: 'australische-pty-ltd-gruenden',
    sku: 'EUROPAN-AU-PTY-LTD-001',
    name: 'Australische Pty Ltd gründen',
    shortDesc: 'Gründung einer australischen Proprietary Limited Company / Pty Ltd mit ASIC-Registrierung, Strukturvorbereitung und optionaler Geschäftsadresse in Sydney, Melbourne, Brisbane oder Perth.',
    price: 2999,
    category: 'Australien',
    flag: '🇦🇺',
    image: '/products/australien-300x300.png',
    heroImage: '/hero/australien.jpg',
    included: [
      'Vorprüfung der geplanten australischen Gesellschaftsstruktur',
      'Namens- und Grunddatenprüfung für die Pty Ltd',
      'Vorbereitung der ASIC-Company-Registration',
      'Strukturierung von Directors, Shareholders und Share Capital',
      'Unterstützung bei schriftlichen Zustimmungen der Officeholders und Shareholders',
      'Koordination der Registered-Office-/Service-Address-Option (Sydney, Melbourne, Brisbane oder Perth)',
      'Gründungsdokumentation und Übergabe der Gesellschaftsunterlagen',
      'Hinweise zu ACN, ABN, GST, TFN und laufenden ASIC-Pflichten',
    ],
    notIncluded: [
      'Automatische Stellung eines australischen Resident Director',
      'ABN / Tax File Number / GST-Registrierung (als gesonderte Option verfügbar)',
      'Registered-Office-/Service-Address (als gesonderte Option verfügbar)',
      'Offizielle ASIC-/Registergebühren',
      'Steuerberatung in Australien oder Deutschland',
      'Buchhaltung, GST-Returns oder Payroll',
      'Bankkontoeröffnung',
      'Visa-, Aufenthalts- oder Immigration-Beratung',
    ],
    addons: [
      'Registered Office / Service Address in Sydney, Melbourne, Brisbane oder Perth',
      'ABN-Unterstützung',
      'ABN + TFN/GST-Vorprüfung',
      'Resident-Director-/Local-Director-Lösung nach gesonderter Due-Diligence-Prüfung',
      'Bankkonto-Unterstützung auf Anfrage',
      'Accounting- / Tax-Support auf Anfrage',
      'Laufende ASIC-/Company-Administration auf Anfrage',
    ],
    process: [
      'Bestellung und Datenübermittlung',
      'Prüfung der Director-Residency-Anforderungen',
      'Vorprüfung der Firmierung',
      'Vorbereitung der Gründungsunterlagen',
      'Gründung der Pty Ltd bei ASIC, Vergabe der ACN',
      'Übergabe der Gesellschaftsdaten',
    ],
    hint: 'Eine australische Pty Ltd benötigt mindestens einen Director, der in Australien lebt. Die Übernahme oder Vermittlung einer Resident-/Local-Director-Funktion erfolgt nicht automatisch, sondern nur nach Due-Diligence-, Zweck- und Risikoprüfung. Preis zzgl. ASIC-/Registergebühren, Adresskosten, externer Providerkosten und Sonderleistungen.',
    tags: ['Pty Ltd', 'Australien', 'Australische Limited', 'Asien-Pazifik', 'Internationale Firmengründung'],
  },
  {
    slug: 'uk-limited-nominee-treuhandadministration',
    sku: 'EUROPAN-UK-NOMINEE-001',
    name: 'UK Limited Nominee- und Treuhandadministration',
    shortDesc: 'Professionelle Nominee- und Treuhandverwaltung für UK Limited Strukturen — dokumentiert, compliance-orientiert und vollständig transparent bezüglich wirtschaftlich Berechtigter.',
    price: null,
    priceLabel: 'Ab individuelles Angebot nach Prüfung',
    inquiry: true,
    category: 'UK / Großbritannien',
    flag: '🇬🇧',
    image: '/products/UKnominee-300x300.png',
    included: [
      'KYC-/AML-Prüfung und Dokumentation wirtschaftlich Berechtigter',
      'Nominee Shareholder / Treuhandverwaltung nach Mandatsprüfung',
      'Nominee Director nach Einzelfallprüfung',
      'Mandats-, Weisungs- und Beschlussdokumentation',
      'Koordination mit UK-Company-Secretary und Registered Office',
      'Laufende Companies-House-Compliance und Annual Confirmation Statement',
    ],
    notIncluded: [
      'Anonyme oder verdeckte Gesellschaftsstrukturen',
      'Verschleierung wirtschaftlich Berechtigter (PSC)',
      'Steuerhinterziehung oder Umgehung steuerlicher Pflichten',
      'Nicht dokumentierte Zahlungsflüsse',
    ],
    addons: [
      'Laufende Buchhaltung und Accounting',
      'Registered Office-Verlängerung',
      'Bankkonto- und Zahlungsadministration nach gesonderter Prüfung',
    ],
    process: [
      'Anfrage und erste Strukturbeschreibung',
      'KYC-/AML- und Compliance-Prüfung',
      'Mandatsannahme und Vertragsgestaltung',
      'Einrichtung der Nominee-/Treuhandstruktur',
      'Laufende Administration und Dokumentation',
    ],
    hint: 'Dieses Angebot dient ausschließlich der professionellen, dokumentierten Gesellschaftsverwaltung. Eine Mandatsannahme erfolgt nur nach vollständiger KYC- und Compliance-Prüfung.',
    tags: ['UK Nominee', 'Treuhand', 'UK Limited', 'Gesellschaftsverwaltung'],
  },
  {
    slug: 'internationale-nominee-treuhandadministration',
    sku: 'EUROPAN-INT-NOMINEE-TRUST-001',
    name: 'Internationale Nominee- und Treuhandadministration',
    shortDesc: 'Jurisdiktionsübergreifende Nominee-, Treuhand- und Mandatsadministration für internationale Gesellschaftsstrukturen — z. B. Hong Kong, Irland, Belize, Nevis, Cayman, Australien oder Neuseeland.',
    price: null,
    priceLabel: 'Ab €2.490 — individuelles Angebot nach Due Diligence',
    inquiry: true,
    category: 'International',
    flag: '🌐',
    image: '/products/int_nominee-300x300.png',
    included: [
      'Internationale Struktur- und Jurisdiktionsprüfung',
      'KYC-/AML-/Sanktions- und Risikoprüfung der Beteiligten',
      'Prüfung und Dokumentation wirtschaftlich Berechtigter / UBO / PSC / RBO',
      'Prüfung von Steueransässigkeit, Mittelherkunft und Geschäftszweck',
      'Koordination mit lokalen Registered Agents und Company Secretaries',
      'Nominee Shareholder / Treuhandverwaltung nach Mandatsprüfung',
      'Mandats-, Weisungs- und Beschlussdokumentation',
      'Laufende Compliance-, Register- und Renewal-Betreuung',
    ],
    notIncluded: [
      'Anonyme oder verdeckte Gesellschaftsstrukturen',
      'Verschleierung wirtschaftlich Berechtigter',
      'Steuerhinterziehung oder Umgehung steuerlicher Pflichten',
      'Verdeckte Drittzahlungen oder nicht nachvollziehbare Zahlungsflüsse',
      'Insolvenzverschleppung oder Gläubigerbenachteiligung',
    ],
    addons: [
      'Bankkonto- und Zahlungsadministration nach gesonderter Prüfung',
      'Multi-Jurisdiction-Holding-Strukturen nach individuellem Angebot',
    ],
    process: [
      'Anfrage und Strukturbeschreibung',
      'Internationale Due-Diligence-Prüfung',
      'Struktur- und Jurisdiktionsanalyse',
      'Mandatsannahme nach Prüfung',
      'Einrichtung der internationalen Struktur',
      'Laufende Compliance-Administration',
    ],
    hint: 'Dieses Angebot ist kein automatisch bestellbares Standardprodukt. Die endgültige Annahme, Strukturfreigabe und Preisbestätigung erfolgen ausschließlich nach individueller Due-Diligence-Prüfung. Nominee Director ab €7.900/Jahr, komplexe Strukturen ab €14.900/Jahr.',
    tags: ['Internationale Nominee', 'Treuhand', 'Asset Protection', 'Holding', 'Multi-Jurisdiction'],
  },
  {
    slug: 'deutsche-treuhand-mandatsadministration',
    sku: 'EUROPAN-DE-TREUHAND-NOMINEE-001',
    name: 'Deutsche Treuhand- und Mandatsadministration',
    shortDesc: 'Premium-Angebot für deutsche Treuhand-, Mandats- und Verwaltungsstrukturen — ausschließlich nach erweiterter Due-Diligence-, UBO-, Steuer- und Risikoprüfung. Keine verdeckte Firmenbeerdigung.',
    price: null,
    priceLabel: 'Erstprüfung ab €2.490 — Administration ab €9.900/Jahr, nach Vorprüfung',
    inquiry: true,
    category: 'Deutschland',
    flag: '🇩🇪',
    image: '/products/DEnominee-300x300.png',
    included: [
      'Erstprüfung der gesellschaftsrechtlichen Struktur',
      'Erweiterte KYC-/AML-Prüfung der wirtschaftlich Berechtigten',
      'Prüfung von Transparenzregister-, UBO- und Beteiligungsangaben',
      'Prüfung von Steueransässigkeit, Mittelherkunft und Nutzungszweck',
      'Risikoprüfung für Geschäftsführungs-, Beteiligungs- oder Treuhandfunktionen',
      'Schriftliche Mandats- und Weisungsdokumentation',
      'Laufende Compliance- und Dokumentationsverwaltung',
      'Koordination mit Steuerberater, Rechtsanwalt oder Notar, soweit erforderlich',
    ],
    notIncluded: [
      'Anonyme oder verdeckte Gesellschaftsstrukturen',
      'Verschleierung wirtschaftlich Berechtigter',
      'Steuerhinterziehung oder Umgehung steuerlicher Pflichten',
      'Verdeckte Drittzahlungen oder nicht nachvollziehbare Zahlungsflüsse',
      'Insolvenzverschleppung, Gläubigerbenachteiligung oder Vermögensverschiebungen',
      'Konstruktionen, bei denen der tatsächliche Zweck nicht vollständig offengelegt wird',
    ],
    addons: [
      'Digitale Kontoanbieter: Finom / bunq Vorprüfung',
      'High-Street-Banken: Deutsche Bank / Commerzbank / HVB',
      'Komplexe Bankprüfung mit Treuhand-/Organfunktion',
      'Geschäftsführungs-, Organ- oder besondere Zahlungsadministration',
    ],
    process: [
      'Anfrage und erste Strukturbeschreibung',
      'Erweiterte KYC-/AML- und Compliance-Prüfung',
      'Prüfung von UBO, Steueransässigkeit und Mittelherkunft',
      'Mandatsannahme und Vertragsgestaltung nach Prüfung',
      'Einrichtung der Treuhand-/Mandatsstruktur',
      'Laufende Compliance- und Dokumentationsverwaltung',
    ],
    hint: 'Dieses Angebot dient ausdrücklich nicht der verdeckten "Firmenbeerdigung", dem Herauslösen von Altverantwortlichen aus einer problematischen Gesellschaft oder der Verschleierung einer insolvenzreifen Situation. Bei Hinweisen auf unzulässige Nutzung wird kein Mandat übernommen bzw. ein laufendes sofort beendet. Kein automatisch bestellbares Standardprodukt — Preisbestätigung erst nach individueller Due-Diligence-Prüfung.',
    tags: ['Treuhand', 'Mandatsverwaltung', 'Deutschland', 'Compliance'],
  },
  {
    slug: 'uk-limited-jahresadministration',
    sku: 'EUROPAN-UK-LTD-ADMIN-001',
    name: 'UK Limited Jahresadministration',
    shortDesc: 'Laufende Verwaltung Ihrer UK Limited für 12 Monate: Fristenkontrolle, Companies-House-Einreichungen, Confirmation Statement, Registerdatenprüfung und UK-Compliance-Unterstützung.',
    price: null,
    priceLabel: 'Ab €399/Jahr — Dormant, Active oder Premium, je nach Variante',
    inquiry: true,
    category: 'UK / Großbritannien',
    flag: '🇬🇧',
    image: '/products/UKadministration-300x300.png',
    included: [
      'Prüfung der aktuellen Companies-House-Daten',
      'Fristenkontrolle für Confirmation Statement und Accounts',
      'Vorbereitung und Einreichung des Confirmation Statement',
      'Prüfung von Directors, PSCs, Shareholders und SIC-Code',
      'Prüfung von Registered Office und Registered Email Address',
      'Unterstützung bei einfachen Companies-House-Änderungen',
      'Unterstützung bei dormant accounts, soweit passend',
      'Erinnerung an HMRC-/Corporation-Tax-relevante Fristen',
      'Jährlicher Compliance-Check',
    ],
    notIncluded: [
      'Steuerberatung',
      'Buchhaltung, komplexe Jahresabschlüsse, VAT-Returns, PAYE/Payroll',
      'Bankkontoeröffnung',
      'Rechtliche oder steuerliche Strukturberatung',
      'HMRC-Streitfälle',
      'Sanierung stark verspäteter oder bereits auffälliger Gesellschaften',
    ],
    addons: [
      'Dormant Limited Administration',
      'Active Limited Administration',
      'Premium Limited Administration',
    ],
    process: [
      'Bestellung und Übermittlung der Gesellschaftsdaten',
      'Prüfung des aktuellen Companies-House-Status',
      'Klärung von Confirmation Statement und Accounts-Fristen',
      'Laufende Fristenkontrolle über 12 Monate',
      'Einreichung des Confirmation Statement',
      'Jährlicher Compliance-Check',
    ],
    hint: 'Der Companies House Authentication Code wird nicht direkt im Bestellprozess abgefragt — nach der Bestellung erhalten Sie eine gesonderte Anweisung zur sicheren Übermittlung. Die Betreuung läuft 12 Monate ab Auftragsannahme und verlängert sich nicht automatisch. Alle Preise zzgl. amtlicher Gebühren und externer Kosten.',
    tags: ['UK Limited', 'Jahresadministration', 'Companies House', 'Compliance'],
  },
  {
    slug: 'geschaeftsadresse-pan-office',
    sku: 'EUROPAN-PANOFFICE-ADDR-001',
    name: 'Geschäftsadresse buchen',
    shortDesc: 'Digitale Geschäftsadresse an über 100 Standorten weltweit — sofort buchbar, mit digitaler Postverwaltung. Ab 3 Standorten in einer Buchung gilt automatisch der Mengenrabatt.',
    price: null,
    priceLabel: 'Ab €29,00/Monat — direkt bei pan-office.de',
    category: 'PAN21-Netzwerk',
    flag: '📍',
    image: 'https://pan-office.de/logo.png',
    heroImage: '/hero/pan-office.jpg',
    included: [
      'Über 100 Standorte weltweit zur Wahl',
      'Digitale Postverwaltung',
      'Sofort buchbar, kein Mietvertrag',
      'Mengenrabatt ab 3 Standorten',
      '2% EUROPAN-Bonus bei jeder Buchung',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'Dieses Angebot wird direkt bei pan-office.de gebucht — dort sind die aktuellen Standorte, Preise und Verfügbarkeiten immer live einsehbar.',
    externalUrl: 'https://pan-office.de/clients',
    tags: ['Geschäftsadresse', 'Postbox', 'pan-office'],
  },
  {
    slug: 'europan-guthaben-aufladen',
    sku: 'EUROPAN-VOUCHER-001',
    name: 'EUROPAN-Guthaben aufladen',
    shortDesc: 'Laden Sie Ihr EUROPAN-Guthaben direkt auf — per Kreditkarte oder Überweisung, wählbarer Betrag. Einlösbar netzwerkweit, u.a. hier im Shop für den Doppel-Wums-Bonus.',
    price: null,
    priceLabel: 'Wählbarer Betrag — direkt bei europan.group',
    category: 'PAN21-Netzwerk',
    flag: '🎁',
    image: 'https://europan.group/europan-logo.png',
    heroImage: '/hero/europan-guthaben.jpg',
    included: [
      'Sofortige Gutschrift bei Kartenzahlung',
      'Wählbarer Betrag',
      'Netzwerkweit einlösbar (Shop, pan-office.de u.a.)',
      'Voraussetzung für den Doppel-Wums-Bonus',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'Dieses Angebot wird direkt bei europan.group abgewickelt.',
    externalUrl: 'https://europan.group/buy',
    tags: ['EUROPAN', 'Guthaben', 'Gutschein'],
  },
  {
    slug: 'webhosting-1euro-hosting',
    sku: 'EUROPAN-HOSTING-001',
    name: 'WordPress-Webhosting',
    shortDesc: 'WordPress-Hosting ab 1 €/Monat — monatlich kündbar, mit kostenloser Subdomain oder eigener Domain. Ideal als Ergänzung zur neuen Geschäftsadresse oder Firmengründung.',
    price: null,
    priceLabel: 'Ab €1,00/Monat — direkt bei 1euro-hosting.de',
    category: 'PAN21-Netzwerk',
    flag: '🌐',
    image: 'https://1euro-hosting.de/logo.png',
    heroImage: '/hero/1euro-hosting.jpg',
    included: [
      'WordPress-Hosting ab 1 €/Monat',
      'Monatlich kündbar',
      'Kostenlose Subdomain oder eigene Domain ab 9,90 €/Jahr',
      'Basic (3 €) und Pro (9,90 €) ohne Werbeeinblendungen',
    ],
    notIncluded: [],
    addons: [],
    process: [],
    hint: 'Dieses Angebot wird direkt bei 1euro-hosting.de gebucht.',
    externalUrl: 'https://1euro-hosting.de',
    tags: ['Hosting', 'WordPress', 'Webhosting'],
  },
]

export const CATEGORIES = [
  { id: 'alle', label: 'Alle' },
  { id: 'PAN21-Netzwerk', label: '⭐ PAN21-Netzwerk' },
  { id: 'Deutschland', label: '🇩🇪 Deutschland' },
  { id: 'UK / Großbritannien', label: '🇬🇧 UK' },
  { id: 'USA', label: '🇺🇸 USA' },
  { id: 'Hong Kong', label: '🇭🇰 Hong Kong' },
  { id: 'Irland', label: '🇮🇪 Irland' },
  { id: 'Neuseeland', label: '🇳🇿 Neuseeland' },
  { id: 'Australien', label: '🇦🇺 Australien' },
  { id: 'Nevis', label: '🏝️ Nevis' },
  { id: 'Belize', label: '🏝️ Belize' },
  { id: 'International', label: '🌐 International' },
]
